"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from .ledgeraccountsubject import LedgerAccountSubject
from .walletsubject import WalletSubject
from typing import Union

Subject = Union[LedgerAccountSubject, WalletSubject]
