"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from .v2transaction import V2Transaction
from dataclasses_json import Undefined, dataclass_json
from sdk import utils
from typing import Optional, Union


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class V2BulkElementResultErrorSchemas:
    error_code: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('errorCode') }})
    error_description: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('errorDescription') }})
    response_type: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('responseType') }})
    error_details: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('errorDetails'), 'exclude': lambda f: f is None }})
    



@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class V2BulkElementResultDeleteMetadataSchemas:
    response_type: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('responseType') }})
    



@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class V2BulkElementResultRevertTransactionSchemas:
    data: V2Transaction = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('data') }})
    response_type: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('responseType') }})
    



@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class Schemas:
    response_type: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('responseType') }})
    



@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class V2BulkElementResultCreateTransactionSchemas:
    data: V2Transaction = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('data') }})
    response_type: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('responseType') }})
    


V2BulkElementResult = Union[V2BulkElementResultCreateTransactionSchemas, Schemas, V2BulkElementResultRevertTransactionSchemas, V2BulkElementResultDeleteMetadataSchemas, V2BulkElementResultErrorSchemas]
