"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .v2stagedelay import V2StageDelay
from .v2stagesend import V2StageSend
from .v2stagewaitevent import V2StageWaitEvent
from .v2update import V2Update
from typing import Union

V2Stage = Union[V2StageSend, V2StageDelay, V2StageWaitEvent, V2Update]
