"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from formance_sdk_python.models.reconciliation import (
    acceptalertrequest as reconciliation_acceptalertrequest,
    alertresponse as reconciliation_alertresponse,
)
from formance_sdk_python.types import BaseModel, UNSET_SENTINEL
from formance_sdk_python.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import httpx
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class AcceptAlertRequestTypedDict(TypedDict):
    accept_alert_request: reconciliation_acceptalertrequest.AcceptAlertRequestTypedDict
    alert_id: str
    r"""The alert ID."""


class AcceptAlertRequest(BaseModel):
    accept_alert_request: Annotated[
        reconciliation_acceptalertrequest.AcceptAlertRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]

    alert_id: Annotated[
        str,
        pydantic.Field(alias="alertID"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The alert ID."""


class AcceptAlertResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    alert_response: NotRequired[reconciliation_alertresponse.AlertResponseTypedDict]
    r"""OK"""


class AcceptAlertResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    alert_response: Optional[reconciliation_alertresponse.AlertResponse] = None
    r"""OK"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["AlertResponse"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
