"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from formance_sdk_python.models.shared import (
    addaccounttopoolrequest as shared_addaccounttopoolrequest,
)
from formance_sdk_python.types import BaseModel
from formance_sdk_python.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import httpx
import pydantic
from typing_extensions import Annotated, TypedDict


class AddAccountToPoolRequestTypedDict(TypedDict):
    add_account_to_pool_request: (
        shared_addaccounttopoolrequest.AddAccountToPoolRequestTypedDict
    )
    pool_id: str
    r"""The pool ID."""


class AddAccountToPoolRequest(BaseModel):
    add_account_to_pool_request: Annotated[
        shared_addaccounttopoolrequest.AddAccountToPoolRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]

    pool_id: Annotated[
        str,
        pydantic.Field(alias="poolId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The pool ID."""


class AddAccountToPoolResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""


class AddAccountToPoolResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
