"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from formance_sdk_python.models.auth import (
    createsecretresponse as auth_createsecretresponse,
    secretoptions_1 as auth_secretoptions_1,
)
from formance_sdk_python.types import BaseModel, UNSET_SENTINEL
from formance_sdk_python.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import httpx
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


CREATE_SECRET_SERVERS = [
    "http://localhost:8080/",
]


class CreateSecretRequestTypedDict(TypedDict):
    client_id: str
    r"""Client ID"""
    secret_options: NotRequired[auth_secretoptions_1.SecretOptions1TypedDict]


class CreateSecretRequest(BaseModel):
    client_id: Annotated[
        str,
        pydantic.Field(alias="clientId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Client ID"""

    secret_options: Annotated[
        Optional[auth_secretoptions_1.SecretOptions1],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["SecretOptions"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class CreateSecretResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    create_secret_response: NotRequired[
        auth_createsecretresponse.CreateSecretResponseTypedDict
    ]
    r"""Created secret"""


class CreateSecretResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    create_secret_response: Optional[auth_createsecretresponse.CreateSecretResponse] = (
        None
    )
    r"""Created secret"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["CreateSecretResponse"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
