"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from formance_sdk_python.types import BaseModel
from formance_sdk_python.utils import FieldMetadata, PathParamMetadata
import httpx
import pydantic
from typing_extensions import Annotated, TypedDict


class DeleteSecretRequestTypedDict(TypedDict):
    client_id: str
    r"""Client ID"""
    secret_id: str
    r"""Secret ID"""


class DeleteSecretRequest(BaseModel):
    client_id: Annotated[
        str,
        pydantic.Field(alias="clientId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Client ID"""

    secret_id: Annotated[
        str,
        pydantic.Field(alias="secretId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Secret ID"""


class DeleteSecretResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""


class DeleteSecretResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
