"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from formance_sdk_python.models.reconciliation import (
    policyresponse as reconciliation_policyresponse,
)
from formance_sdk_python.types import BaseModel, UNSET_SENTINEL
from formance_sdk_python.utils import FieldMetadata, PathParamMetadata
import httpx
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


GET_POLICY_SERVERS = [
    "http://localhost:8080/",
]


class GetPolicyRequestTypedDict(TypedDict):
    policy_id: str
    r"""The policy ID."""


class GetPolicyRequest(BaseModel):
    policy_id: Annotated[
        str,
        pydantic.Field(alias="policyID"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The policy ID."""


class GetPolicyResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    policy_response: NotRequired[reconciliation_policyresponse.PolicyResponseTypedDict]
    r"""OK"""


class GetPolicyResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    policy_response: Optional[reconciliation_policyresponse.PolicyResponse] = None
    r"""OK"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["PolicyResponse"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
