"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from formance_sdk_python.models.ledger import (
    transactionresponse as ledger_transactionresponse,
)
from formance_sdk_python.types import BaseModel, UNSET_SENTINEL
from formance_sdk_python.utils import FieldMetadata, PathParamMetadata, validate_int
import httpx
from pydantic import model_serializer
from pydantic.functional_validators import BeforeValidator
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


GET_TRANSACTION_SERVERS = [
    "http://localhost:8080/",
]


class GetTransactionRequestTypedDict(TypedDict):
    ledger: str
    r"""Name of the ledger."""
    txid: int
    r"""Transaction ID."""


class GetTransactionRequest(BaseModel):
    ledger: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Name of the ledger."""

    txid: Annotated[
        Annotated[int, BeforeValidator(validate_int)],
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Transaction ID."""


class GetTransactionResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    transaction_response: NotRequired[
        ledger_transactionresponse.TransactionResponseTypedDict
    ]
    r"""OK"""


class GetTransactionResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    transaction_response: Optional[ledger_transactionresponse.TransactionResponse] = (
        None
    )
    r"""OK"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["TransactionResponse"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
