"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from formance_sdk_python.models.shared import (
    connectorsconfigsresponse as shared_connectorsconfigsresponse,
)
from formance_sdk_python.types import BaseModel
import httpx
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ListConfigsAvailableConnectorsResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    connectors_configs_response: NotRequired[
        shared_connectorsconfigsresponse.ConnectorsConfigsResponseTypedDict
    ]
    r"""OK"""


class ListConfigsAvailableConnectorsResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    connectors_configs_response: Optional[
        shared_connectorsconfigsresponse.ConnectorsConfigsResponse
    ] = None
    r"""OK"""
