"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from formance_sdk_python.models.orchestration import (
    listrunsresponse as orchestration_listrunsresponse,
)
from formance_sdk_python.types import BaseModel, UNSET_SENTINEL
from formance_sdk_python.utils import FieldMetadata, QueryParamMetadata
import httpx
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


LIST_INSTANCES_SERVERS = [
    "http://localhost:8080/",
]


class ListInstancesRequestTypedDict(TypedDict):
    running: NotRequired[bool]
    r"""Filter running instances"""
    workflow_id: NotRequired[str]
    r"""A workflow id"""


class ListInstancesRequest(BaseModel):
    running: Annotated[
        Optional[bool],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filter running instances"""

    workflow_id: Annotated[
        Optional[str],
        pydantic.Field(alias="workflowID"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""A workflow id"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["running", "workflowID"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ListInstancesResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    list_runs_response: NotRequired[
        orchestration_listrunsresponse.ListRunsResponseTypedDict
    ]
    r"""List of workflow instances"""


class ListInstancesResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    list_runs_response: Optional[orchestration_listrunsresponse.ListRunsResponse] = None
    r"""List of workflow instances"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["ListRunsResponse"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
