"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from formance_sdk_python.models.webhooks import configuser as webhooks_configuser
from formance_sdk_python.types import BaseModel
from formance_sdk_python.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import httpx
from typing_extensions import Annotated, TypedDict


UPDATE_CONFIG_SERVERS = [
    "http://localhost:8080/",
]


class UpdateConfigRequestTypedDict(TypedDict):
    config_user: webhooks_configuser.ConfigUserTypedDict
    id: str
    r"""Config ID"""


class UpdateConfigRequest(BaseModel):
    config_user: Annotated[
        webhooks_configuser.ConfigUser,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]

    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Config ID"""


class UpdateConfigResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""


class UpdateConfigResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
