"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from formance_sdk_python.models.payments import (
    updatepoolqueryrequest as payments_updatepoolqueryrequest,
)
from formance_sdk_python.types import BaseModel
from formance_sdk_python.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import httpx
import pydantic
from typing_extensions import Annotated, TypedDict


UPDATE_POOL_QUERY_SERVERS = [
    "http://localhost:8080/",
]


class UpdatePoolQueryRequestTypedDict(TypedDict):
    update_pool_query_request: (
        payments_updatepoolqueryrequest.UpdatePoolQueryRequestTypedDict
    )
    pool_id: str
    r"""The pool ID."""


class UpdatePoolQueryRequest(BaseModel):
    update_pool_query_request: Annotated[
        payments_updatepoolqueryrequest.UpdatePoolQueryRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]

    pool_id: Annotated[
        str,
        pydantic.Field(alias="poolId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The pool ID."""


class UpdatePoolQueryResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""


class UpdatePoolQueryResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
