"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from formance_sdk_python.models.orchestration import (
    v2createtriggerresponse as orchestration_v2createtriggerresponse,
)
from formance_sdk_python.types import BaseModel, UNSET_SENTINEL
import httpx
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


V2_CREATE_TRIGGER_SERVERS = [
    "http://localhost:8080/",
]


class V2CreateTriggerResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    v2_create_trigger_response: NotRequired[
        orchestration_v2createtriggerresponse.V2CreateTriggerResponseTypedDict
    ]
    r"""Created trigger"""


class V2CreateTriggerResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    v2_create_trigger_response: Optional[
        orchestration_v2createtriggerresponse.V2CreateTriggerResponse
    ] = None
    r"""Created trigger"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["V2CreateTriggerResponse"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
