"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from formance_sdk_python.models.shared import (
    v2createledgerrequest as shared_v2createledgerrequest,
)
from formance_sdk_python.types import BaseModel
from formance_sdk_python.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import httpx
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class V2CreateLedgerRequestTypedDict(TypedDict):
    ledger: str
    r"""Name of the ledger."""
    v2_create_ledger_request: NotRequired[
        shared_v2createledgerrequest.V2CreateLedgerRequestTypedDict
    ]


class V2CreateLedgerRequest(BaseModel):
    ledger: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Name of the ledger."""

    v2_create_ledger_request: Annotated[
        Optional[shared_v2createledgerrequest.V2CreateLedgerRequest],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ] = None


class V2CreateLedgerResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""


class V2CreateLedgerResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
