"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from formance_sdk_python.models.shared import v2exporter as shared_v2exporter
from formance_sdk_python.types import BaseModel
import httpx
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class V2ListExportersCursor2TypedDict(TypedDict):
    data: List[shared_v2exporter.V2ExporterTypedDict]
    has_more: bool
    page_size: int
    next: NotRequired[str]
    previous: NotRequired[str]


class V2ListExportersCursor2(BaseModel):
    data: List[shared_v2exporter.V2Exporter]

    has_more: Annotated[bool, pydantic.Field(alias="hasMore")]

    page_size: Annotated[int, pydantic.Field(alias="pageSize")]

    next: Optional[str] = None

    previous: Optional[str] = None


class V2ListExportersCursor1TypedDict(TypedDict):
    cursor: V2ListExportersCursor2TypedDict
    data: NotRequired[List[shared_v2exporter.V2ExporterTypedDict]]


class V2ListExportersCursor1(BaseModel):
    cursor: V2ListExportersCursor2

    data: Optional[List[shared_v2exporter.V2Exporter]] = None


class V2ListExportersResponseBodyTypedDict(TypedDict):
    r"""Exporters list"""

    cursor: NotRequired[V2ListExportersCursor1TypedDict]


class V2ListExportersResponseBody(BaseModel):
    r"""Exporters list"""

    cursor: Optional[V2ListExportersCursor1] = None


class V2ListExportersResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    object: NotRequired[V2ListExportersResponseBodyTypedDict]
    r"""Exporters list"""


class V2ListExportersResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    object: Optional[V2ListExportersResponseBody] = None
    r"""Exporters list"""
