"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from formance_sdk_python.models.ledger import v2errorresponse as ledger_v2errorresponse
from formance_sdk_python.types import BaseModel, UNSET_SENTINEL
from formance_sdk_python.utils import FieldMetadata, PathParamMetadata
import httpx
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


V2_RESTORE_BUCKET_SERVERS = [
    "http://localhost:8080/",
]


class V2RestoreBucketRequestTypedDict(TypedDict):
    bucket: str
    r"""The bucket name"""


class V2RestoreBucketRequest(BaseModel):
    bucket: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The bucket name"""


class V2RestoreBucketResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    v2_error_response: NotRequired[ledger_v2errorresponse.V2ErrorResponseTypedDict]
    r"""Bucket not found"""


class V2RestoreBucketResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    v2_error_response: Optional[ledger_v2errorresponse.V2ErrorResponse] = None
    r"""Bucket not found"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["V2ErrorResponse"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
