"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from formance_sdk_python.models.ledger import (
    v2exporterconfiguration as ledger_v2exporterconfiguration,
)
from formance_sdk_python.types import BaseModel
from formance_sdk_python.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import httpx
import pydantic
from typing_extensions import Annotated, TypedDict


class V2UpdateExporterRequestTypedDict(TypedDict):
    v2_exporter_configuration: (
        ledger_v2exporterconfiguration.V2ExporterConfigurationTypedDict
    )
    exporter_id: str
    r"""The exporter id"""


class V2UpdateExporterRequest(BaseModel):
    v2_exporter_configuration: Annotated[
        ledger_v2exporterconfiguration.V2ExporterConfiguration,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]

    exporter_id: Annotated[
        str,
        pydantic.Field(alias="exporterID"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The exporter id"""


class V2UpdateExporterResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""


class V2UpdateExporterResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
