"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from formance_sdk_python.models.payments import (
    v3paymentserviceuserlinkattempt as payments_v3paymentserviceuserlinkattempt,
)
from formance_sdk_python.types import BaseModel, UNSET_SENTINEL
from formance_sdk_python.utils import FieldMetadata, PathParamMetadata
import httpx
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


V3_GET_PAYMENT_SERVICE_USER_LINK_ATTEMPT_FROM_CONNECTOR_ID_SERVERS = [
    "http://localhost:8080/",
]


class V3GetPaymentServiceUserLinkAttemptFromConnectorIDRequestTypedDict(TypedDict):
    attempt_id: str
    r"""The attempt ID"""
    connector_id: str
    r"""The connector ID"""
    payment_service_user_id: str
    r"""The payment service user ID"""


class V3GetPaymentServiceUserLinkAttemptFromConnectorIDRequest(BaseModel):
    attempt_id: Annotated[
        str,
        pydantic.Field(alias="attemptID"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The attempt ID"""

    connector_id: Annotated[
        str,
        pydantic.Field(alias="connectorID"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The connector ID"""

    payment_service_user_id: Annotated[
        str,
        pydantic.Field(alias="paymentServiceUserID"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The payment service user ID"""


class V3GetPaymentServiceUserLinkAttemptFromConnectorIDResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    v3_payment_service_user_link_attempt: NotRequired[
        payments_v3paymentserviceuserlinkattempt.V3PaymentServiceUserLinkAttemptTypedDict
    ]
    r"""OK"""


class V3GetPaymentServiceUserLinkAttemptFromConnectorIDResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    v3_payment_service_user_link_attempt: Optional[
        payments_v3paymentserviceuserlinkattempt.V3PaymentServiceUserLinkAttempt
    ] = None
    r"""OK"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["V3PaymentServiceUserLinkAttempt"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
