"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from formance_sdk_python.models.shared import (
    v3resetconnectorresponse as shared_v3resetconnectorresponse,
)
from formance_sdk_python.types import BaseModel
from formance_sdk_python.utils import FieldMetadata, PathParamMetadata
import httpx
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class V3ResetConnectorRequestTypedDict(TypedDict):
    connector_id: str
    r"""The connector ID"""


class V3ResetConnectorRequest(BaseModel):
    connector_id: Annotated[
        str,
        pydantic.Field(alias="connectorID"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The connector ID"""


class V3ResetConnectorResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    v3_reset_connector_response: NotRequired[
        shared_v3resetconnectorresponse.V3ResetConnectorResponseTypedDict
    ]
    r"""Accepted"""


class V3ResetConnectorResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    v3_reset_connector_response: Optional[
        shared_v3resetconnectorresponse.V3ResetConnectorResponse
    ] = None
    r"""Accepted"""
