"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import Any, TYPE_CHECKING

from formance_sdk_python.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .security import Security, SecurityTypedDict

__all__ = ["Security", "SecurityTypedDict"]

_dynamic_imports: dict[str, str] = {
    "Security": ".security",
    "SecurityTypedDict": ".security",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
