"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .volume import Volume, VolumeTypedDict
from formance_sdk_python.types import BaseModel
from formance_sdk_python.utils import validate_int
from pydantic.functional_validators import BeforeValidator
from typing import Any, Dict, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class AccountWithVolumesAndBalancesTypedDict(TypedDict):
    address: str
    balances: NotRequired[Dict[str, int]]
    metadata: NotRequired[Dict[str, Any]]
    type: NotRequired[str]
    volumes: NotRequired[Dict[str, VolumeTypedDict]]


class AccountWithVolumesAndBalances(BaseModel):
    address: str

    balances: Optional[Dict[str, Annotated[int, BeforeValidator(validate_int)]]] = None

    metadata: Optional[Dict[str, Any]] = None

    type: Optional[str] = None

    volumes: Optional[Dict[str, Volume]] = None
