"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from formance_sdk_python.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class BankingCircleConfigTypedDict(TypedDict):
    authorization_endpoint: str
    endpoint: str
    name: str
    password: str
    user_certificate: str
    user_certificate_key: str
    username: str
    polling_period: NotRequired[str]
    r"""The frequency at which the connector will try to fetch new BalanceTransaction objects from Banking Circle API.

    """


class BankingCircleConfig(BaseModel):
    authorization_endpoint: Annotated[
        str, pydantic.Field(alias="authorizationEndpoint")
    ]

    endpoint: str

    name: str

    password: str

    user_certificate: Annotated[str, pydantic.Field(alias="userCertificate")]

    user_certificate_key: Annotated[str, pydantic.Field(alias="userCertificateKey")]

    username: str

    polling_period: Annotated[Optional[str], pydantic.Field(alias="pollingPeriod")] = (
        "120s"
    )
    r"""The frequency at which the connector will try to fetch new BalanceTransaction objects from Banking Circle API.

    """
