"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from formance_sdk_python.types import BaseModel
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ConfigUserTypedDict(TypedDict):
    endpoint: str
    event_types: List[str]
    name: NotRequired[str]
    secret: NotRequired[str]


class ConfigUser(BaseModel):
    endpoint: str

    event_types: Annotated[List[str], pydantic.Field(alias="eventTypes")]

    name: Optional[str] = None

    secret: Optional[str] = None
