"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from formance_sdk_python.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class KeyTypedDict(TypedDict):
    data_type: str
    required: bool


class Key(BaseModel):
    data_type: Annotated[str, pydantic.Field(alias="dataType")]

    required: bool


class ConnectorsConfigsResponseConnectorTypedDict(TypedDict):
    key: KeyTypedDict


class ConnectorsConfigsResponseConnector(BaseModel):
    key: Key


class ConnectorsConfigsResponseDataTypedDict(TypedDict):
    connector: ConnectorsConfigsResponseConnectorTypedDict


class ConnectorsConfigsResponseData(BaseModel):
    connector: ConnectorsConfigsResponseConnector


class ConnectorsConfigsResponseTypedDict(TypedDict):
    r"""OK"""

    data: ConnectorsConfigsResponseDataTypedDict


class ConnectorsConfigsResponse(BaseModel):
    r"""OK"""

    data: ConnectorsConfigsResponseData
