"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .trigger import Trigger, TriggerTypedDict
from formance_sdk_python.types import BaseModel
from typing_extensions import TypedDict


class CreateTriggerResponseTypedDict(TypedDict):
    data: TriggerTypedDict


class CreateTriggerResponse(BaseModel):
    data: Trigger
