"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from formance_sdk_python.types import BaseModel
from typing import Any, Dict, Optional
from typing_extensions import NotRequired, TypedDict


class CreateSecretRequestTypedDict(TypedDict):
    name: str
    metadata: NotRequired[Dict[str, Any]]


class CreateSecretRequest(BaseModel):
    name: str

    metadata: Optional[Dict[str, Any]] = None
