"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .subject import Subject, SubjectTypedDict
from formance_sdk_python.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Dict, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class HoldTypedDict(TypedDict):
    asset: str
    description: str
    id: str
    r"""The unique ID of the hold."""
    metadata: Dict[str, str]
    r"""Metadata associated with the hold."""
    wallet_id: str
    r"""The ID of the wallet the hold is associated with."""
    destination: NotRequired[SubjectTypedDict]


class Hold(BaseModel):
    asset: str

    description: str

    id: str
    r"""The unique ID of the hold."""

    metadata: Dict[str, str]
    r"""Metadata associated with the hold."""

    wallet_id: Annotated[str, pydantic.Field(alias="walletID")]
    r"""The ID of the wallet the hold is associated with."""

    destination: Optional[Subject] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["destination"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    Hold.model_rebuild()
except NameError:
    pass
