"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .orchestrationpaymentstatus import OrchestrationPaymentStatus
from datetime import datetime
from formance_sdk_python.types import BaseModel
from formance_sdk_python.utils import validate_int
import pydantic
from pydantic.functional_validators import BeforeValidator
from typing_extensions import Annotated, TypedDict


class OrchestrationPaymentAdjustmentRawTypedDict(TypedDict):
    pass


class OrchestrationPaymentAdjustmentRaw(BaseModel):
    pass


class OrchestrationPaymentAdjustmentTypedDict(TypedDict):
    absolute: bool
    amount: int
    date_: datetime
    raw: OrchestrationPaymentAdjustmentRawTypedDict
    status: OrchestrationPaymentStatus


class OrchestrationPaymentAdjustment(BaseModel):
    absolute: bool

    amount: Annotated[int, BeforeValidator(validate_int)]

    date_: Annotated[datetime, pydantic.Field(alias="date")]

    raw: OrchestrationPaymentAdjustmentRaw

    status: OrchestrationPaymentStatus
