"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .paymentstatus import PaymentStatus
from datetime import datetime
from formance_sdk_python.types import BaseModel
from formance_sdk_python.utils import validate_int
import pydantic
from pydantic.functional_validators import BeforeValidator
from typing_extensions import Annotated, TypedDict


class PaymentAdjustmentRawTypedDict(TypedDict):
    pass


class PaymentAdjustmentRaw(BaseModel):
    pass


class PaymentAdjustmentTypedDict(TypedDict):
    amount: int
    created_at: datetime
    raw: PaymentAdjustmentRawTypedDict
    reference: str
    status: PaymentStatus


class PaymentAdjustment(BaseModel):
    amount: Annotated[int, BeforeValidator(validate_int)]

    created_at: Annotated[datetime, pydantic.Field(alias="createdAt")]

    raw: PaymentAdjustmentRaw

    reference: str

    status: PaymentStatus
