"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from formance_sdk_python.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class PaymentsServerInfoTypedDict(TypedDict):
    r"""Server information"""

    debug: NotRequired[bool]
    version: NotRequired[str]


class PaymentsServerInfo(BaseModel):
    r"""Server information"""

    debug: Optional[bool] = None

    version: Optional[str] = None
