"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from formance_sdk_python.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Any, Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TotalTypedDict(TypedDict):
    relation: NotRequired[str]
    value: NotRequired[int]


class Total(BaseModel):
    relation: Optional[str] = None

    value: Optional[int] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["relation", "value"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ResponseCursorTypedDict(TypedDict):
    data: NotRequired[List[Dict[str, Any]]]
    has_more: NotRequired[bool]
    next: NotRequired[str]
    page_size: NotRequired[int]
    previous: NotRequired[str]
    total: NotRequired[TotalTypedDict]


class ResponseCursor(BaseModel):
    data: Optional[List[Dict[str, Any]]] = None

    has_more: Annotated[Optional[bool], pydantic.Field(alias="hasMore")] = None

    next: Optional[str] = None

    page_size: Annotated[Optional[int], pydantic.Field(alias="pageSize")] = None

    previous: Optional[str] = None

    total: Optional[Total] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["data", "hasMore", "next", "pageSize", "previous", "total"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ResponseTypedDict(TypedDict):
    cursor: NotRequired[ResponseCursorTypedDict]
    data: NotRequired[Dict[str, Any]]
    r"""The payload"""


class Response(BaseModel):
    cursor: Optional[ResponseCursor] = None

    data: Optional[Dict[str, Any]] = None
    r"""The payload"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["cursor", "data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    ResponseCursor.model_rebuild()
except NameError:
    pass
