"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .stagesenddestinationaccount import (
    StageSendDestinationAccount,
    StageSendDestinationAccountTypedDict,
)
from .stagesenddestinationwallet import (
    StageSendDestinationWallet,
    StageSendDestinationWalletTypedDict,
)
from .stagesendsourcepayment import (
    StageSendSourcePayment,
    StageSendSourcePaymentTypedDict,
)
from formance_sdk_python.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class StageSendSourceTypedDict(TypedDict):
    account: NotRequired[StageSendDestinationAccountTypedDict]
    payment: NotRequired[StageSendSourcePaymentTypedDict]
    wallet: NotRequired[StageSendDestinationWalletTypedDict]


class StageSendSource(BaseModel):
    account: Optional[StageSendDestinationAccount] = None

    payment: Optional[StageSendSourcePayment] = None

    wallet: Optional[StageSendDestinationWallet] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["account", "payment", "wallet"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
