"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from formance_sdk_python.types import BaseModel
from typing_extensions import TypedDict


class StatsTypedDict(TypedDict):
    accounts: int
    transactions: int


class Stats(BaseModel):
    accounts: int

    transactions: int
