"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .v2account import V2Account, V2AccountTypedDict
from formance_sdk_python.types import BaseModel
from typing_extensions import TypedDict


class V2ActivityGetAccountOutputTypedDict(TypedDict):
    data: V2AccountTypedDict


class V2ActivityGetAccountOutput(BaseModel):
    data: V2Account
