"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .v2targetid import V2TargetID, V2TargetIDTypedDict
from .v2targettype import V2TargetType
from formance_sdk_python.types import BaseModel
import pydantic
from typing import Dict, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class V2BulkElementAddMetadataDataTypedDict(TypedDict):
    metadata: Dict[str, str]
    target_id: V2TargetIDTypedDict
    target_type: V2TargetType


class V2BulkElementAddMetadataData(BaseModel):
    metadata: Dict[str, str]

    target_id: Annotated[V2TargetID, pydantic.Field(alias="targetId")]

    target_type: Annotated[V2TargetType, pydantic.Field(alias="targetType")]


class V2BulkElementAddMetadataTypedDict(TypedDict):
    action: str
    data: NotRequired[V2BulkElementAddMetadataDataTypedDict]
    ik: NotRequired[str]


class V2BulkElementAddMetadata(BaseModel):
    action: str

    data: Optional[V2BulkElementAddMetadataData] = None

    ik: Optional[str] = None
