"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .v2bulkelementresult import V2BulkElementResult, V2BulkElementResultTypedDict
from formance_sdk_python.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class V2BulkResponseTypedDict(TypedDict):
    data: List[V2BulkElementResultTypedDict]


class V2BulkResponse(BaseModel):
    data: List[V2BulkElementResult]
