"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from formance_sdk_python.types import BaseModel
from typing import Any, Dict
from typing_extensions import TypedDict


class V2CreateExporterRequestTypedDict(TypedDict):
    config: Dict[str, Any]
    driver: str


class V2CreateExporterRequest(BaseModel):
    config: Dict[str, Any]

    driver: str
