"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .v2subject import V2Subject, V2SubjectTypedDict
from formance_sdk_python.types import BaseModel
import pydantic
from typing import Dict, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class V2HoldTypedDict(TypedDict):
    description: str
    id: str
    r"""The unique ID of the hold."""
    metadata: Dict[str, str]
    r"""Metadata associated with the hold."""
    wallet_id: str
    r"""The ID of the wallet the hold is associated with."""
    destination: NotRequired[V2SubjectTypedDict]


class V2Hold(BaseModel):
    description: str

    id: str
    r"""The unique ID of the hold."""

    metadata: Dict[str, str]
    r"""Metadata associated with the hold."""

    wallet_id: Annotated[str, pydantic.Field(alias="walletID")]
    r"""The ID of the wallet the hold is associated with."""

    destination: Optional[V2Subject] = None
