"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from formance_sdk_python.types import BaseModel
import pydantic
from typing import Dict, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class V2LedgerTypedDict(TypedDict):
    added_at: datetime
    bucket: str
    name: str
    metadata: NotRequired[Dict[str, str]]


class V2Ledger(BaseModel):
    added_at: Annotated[datetime, pydantic.Field(alias="addedAt")]

    bucket: str

    name: str

    metadata: Optional[Dict[str, str]] = None
