"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .v2monetary import V2Monetary, V2MonetaryTypedDict
from .v2stagesenddestination import (
    V2StageSendDestination,
    V2StageSendDestinationTypedDict,
)
from .v2stagesendsource import V2StageSendSource, V2StageSendSourceTypedDict
from datetime import datetime
from formance_sdk_python.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Dict, Optional
from typing_extensions import NotRequired, TypedDict


class V2StageSendTypedDict(TypedDict):
    amount: NotRequired[V2MonetaryTypedDict]
    destination: NotRequired[V2StageSendDestinationTypedDict]
    metadata: NotRequired[Dict[str, str]]
    source: NotRequired[V2StageSendSourceTypedDict]
    timestamp: NotRequired[datetime]


class V2StageSend(BaseModel):
    amount: Optional[V2Monetary] = None

    destination: Optional[V2StageSendDestination] = None

    metadata: Optional[Dict[str, str]] = None

    source: Optional[V2StageSendSource] = None

    timestamp: Optional[datetime] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["amount", "destination", "metadata", "source", "timestamp"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
