"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .v3paymentstatusenum import V3PaymentStatusEnum
from datetime import datetime
from formance_sdk_python.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from formance_sdk_python.utils import validate_int
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import BeforeValidator
from typing import Dict, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class V3CreatePaymentAdjustmentRequestTypedDict(TypedDict):
    created_at: datetime
    reference: str
    status: V3PaymentStatusEnum
    amount: NotRequired[int]
    asset: NotRequired[str]
    metadata: NotRequired[Nullable[Dict[str, str]]]


class V3CreatePaymentAdjustmentRequest(BaseModel):
    created_at: Annotated[datetime, pydantic.Field(alias="createdAt")]

    reference: str

    status: V3PaymentStatusEnum

    amount: Annotated[Optional[int], BeforeValidator(validate_int)] = None

    asset: Optional[str] = None

    metadata: OptionalNullable[Dict[str, str]] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["amount", "asset", "metadata"]
        nullable_fields = ["metadata"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in self.model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
