"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .v3account import V3Account, V3AccountTypedDict
from formance_sdk_python.types import BaseModel
from typing_extensions import TypedDict


class V3GetAccountResponseTypedDict(TypedDict):
    data: V3AccountTypedDict


class V3GetAccountResponse(BaseModel):
    data: V3Account
