"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from formance_sdk_python.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class V3ReversePaymentInitiationResponseDataTypedDict(TypedDict):
    payment_initiation_reversal_id: NotRequired[str]
    r"""Related payment initiation reversal object ID created.

    """
    task_id: NotRequired[str]
    r"""Since this call is asynchronous, the response will contain the ID of the task that was created to reverse the payment initiation. You can use the task API to check the status of the task and get the resulting payment ID.

    """


class V3ReversePaymentInitiationResponseData(BaseModel):
    payment_initiation_reversal_id: Annotated[
        Optional[str], pydantic.Field(alias="paymentInitiationReversalID")
    ] = None
    r"""Related payment initiation reversal object ID created.

    """

    task_id: Annotated[Optional[str], pydantic.Field(alias="taskID")] = None
    r"""Since this call is asynchronous, the response will contain the ID of the task that was created to reverse the payment initiation. You can use the task API to check the status of the task and get the resulting payment ID.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["paymentInitiationReversalID", "taskID"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class V3ReversePaymentInitiationResponseTypedDict(TypedDict):
    data: V3ReversePaymentInitiationResponseDataTypedDict


class V3ReversePaymentInitiationResponse(BaseModel):
    data: V3ReversePaymentInitiationResponseData


try:
    V3ReversePaymentInitiationResponseData.model_rebuild()
except NameError:
    pass
