"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from formance_sdk_python.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class V3UninstallConnectorResponseDataTypedDict(TypedDict):
    task_id: str
    r"""Since this call is asynchronous, the response will contain the ID of the task that was created to uninstall the connector. You can use the task API to check the status of the task and get the results.

    """


class V3UninstallConnectorResponseData(BaseModel):
    task_id: Annotated[str, pydantic.Field(alias="taskID")]
    r"""Since this call is asynchronous, the response will contain the ID of the task that was created to uninstall the connector. You can use the task API to check the status of the task and get the results.

    """


class V3UninstallConnectorResponseTypedDict(TypedDict):
    data: V3UninstallConnectorResponseDataTypedDict


class V3UninstallConnectorResponse(BaseModel):
    data: V3UninstallConnectorResponseData
