"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from formance_sdk_python.types import BaseModel
import pydantic
from typing import List
from typing_extensions import Annotated, TypedDict


class WebhooksConfigTypedDict(TypedDict):
    active: bool
    created_at: datetime
    endpoint: str
    event_types: List[str]
    id: str
    secret: str
    updated_at: datetime


class WebhooksConfig(BaseModel):
    active: bool

    created_at: Annotated[datetime, pydantic.Field(alias="createdAt")]

    endpoint: str

    event_types: Annotated[List[str], pydantic.Field(alias="eventTypes")]

    id: str

    secret: str

    updated_at: Annotated[datetime, pydantic.Field(alias="updatedAt")]
