"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.shared import poolbalancesresponse as shared_poolbalancesresponse
from datetime import datetime
from typing import Optional


@dataclasses.dataclass
class GetPoolBalancesRequest:
    at: datetime = dataclasses.field(metadata={'query_param': { 'field_name': 'at', 'style': 'form', 'explode': True }})
    r"""Filter balances by date."""
    pool_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'poolId', 'style': 'simple', 'explode': False }})
    r"""The pool ID."""
    



@dataclasses.dataclass
class GetPoolBalancesResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    pool_balances_response: Optional[shared_poolbalancesresponse.PoolBalancesResponse] = dataclasses.field(default=None)
    r"""OK"""
    

