"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.shared import listtriggersresponse as shared_listtriggersresponse
from typing import Optional


@dataclasses.dataclass
class ListTriggersRequest:
    name: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'name', 'style': 'form', 'explode': True }})
    r"""search by name"""
    



@dataclasses.dataclass
class ListTriggersResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    list_triggers_response: Optional[shared_listtriggersresponse.ListTriggersResponse] = dataclasses.field(default=None)
    r"""List of triggers"""
    

