"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.shared import attemptresponse as shared_attemptresponse
from typing import Optional


@dataclasses.dataclass
class TestConfigRequest:
    __test__ = False
    
    id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': False }})
    r"""Config ID"""
    



@dataclasses.dataclass
class TestConfigResponse:
    __test__ = False
    
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    attempt_response: Optional[shared_attemptresponse.AttemptResponse] = dataclasses.field(default=None)
    r"""OK"""
    

