"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.shared import v2listtriggersresponse as shared_v2listtriggersresponse
from typing import Optional


@dataclasses.dataclass
class V2ListTriggersResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    v2_list_triggers_response: Optional[shared_v2listtriggersresponse.V2ListTriggersResponse] = dataclasses.field(default=None)
    r"""List of triggers"""
    

