"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.errors import v2error as errors_v2error
from ...models.shared import v2runworkflowresponse as shared_v2runworkflowresponse
from typing import Dict, Optional


@dataclasses.dataclass
class V2RunWorkflowRequest:
    workflow_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'workflowID', 'style': 'simple', 'explode': False }})
    r"""The flow id"""
    request_body: Optional[Dict[str, str]] = dataclasses.field(default=None, metadata={'request': { 'media_type': 'application/json' }})
    wait: Optional[bool] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'wait', 'style': 'form', 'explode': True }})
    r"""Wait end of the workflow before return"""
    



@dataclasses.dataclass
class V2RunWorkflowResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    v2_error: Optional[errors_v2error.V2Error] = dataclasses.field(default=None)
    r"""General error"""
    v2_run_workflow_response: Optional[shared_v2runworkflowresponse.V2RunWorkflowResponse] = dataclasses.field(default=None)
    r"""The workflow instance"""
    

