"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from .sdkconfiguration import SDKConfiguration
from formance_sdk_python.v1 import V1
from formance_sdk_python.v2 import V2


class Ledger(BaseSDK):
    v1: V1
    v2: V2

    def __init__(self, sdk_config: SDKConfiguration) -> None:
        BaseSDK.__init__(self, sdk_config)
        self.sdk_configuration = sdk_config
        self._init_sdks()

    def _init_sdks(self):
        self.v1 = V1(self.sdk_configuration)
        self.v2 = V2(self.sdk_configuration)
