"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from formance_sdk_python import utils
from formance_sdk_python._hooks import HookContext
from formance_sdk_python.models import errors, operations, reconciliation
from formance_sdk_python.models.reconciliation import (
    policyrequest as reconciliation_policyrequest,
)
from formance_sdk_python.types import BaseModel, OptionalNullable, UNSET
from formance_sdk_python.utils.unmarshal_json_response import unmarshal_json_response
from typing import Any, Dict, Mapping, Optional, Union, cast


class ReconciliationV1(BaseSDK):
    def create_policy(
        self,
        *,
        request: Union[
            reconciliation_policyrequest.PolicyRequest,
            reconciliation_policyrequest.PolicyRequestTypedDict,
        ],
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> operations.CreatePolicyResponse:
        r"""Create a policy

        Create a policy

        If set, this operation will use `client_id` from the global security.

        :param request: The request object to send.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = operations.CREATE_POLICY_SERVERS[0]

        if not isinstance(request, BaseModel):
            request = utils.unmarshal(request, reconciliation.PolicyRequest)
        request = cast(reconciliation.PolicyRequest, request)

        req = self._build_request(
            method="POST",
            path="/api/reconciliation/policies",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request, False, False, "json", reconciliation.PolicyRequest
            ),
            allow_empty_value=None,
            allowed_fields=["client_id"],
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="createPolicy",
                oauth2_scopes=["reconciliation:write"],
                security_source=self.sdk_configuration.security,
            ),
            request=req,
            is_error_status_code=lambda c: not utils.match_status_codes(["201"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "201", "application/json"):
            return operations.CreatePolicyResponse(
                policy_response=unmarshal_json_response(
                    Optional[reconciliation.PolicyResponse], http_res
                ),
                status_code=http_res.status_code,
                content_type=http_res.headers.get("Content-Type") or "",
                raw_response=http_res,
            )
        if utils.match_response(http_res, "default", "application/json"):
            response_data = unmarshal_json_response(
                reconciliation.ErrorResponseData, http_res
            )
            raise reconciliation.ErrorResponse(response_data, http_res)

        raise errors.SDKError("Unexpected response received", http_res)

    async def create_policy_async(
        self,
        *,
        request: Union[
            reconciliation_policyrequest.PolicyRequest,
            reconciliation_policyrequest.PolicyRequestTypedDict,
        ],
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> operations.CreatePolicyResponse:
        r"""Create a policy

        Create a policy

        If set, this operation will use `client_id` from the global security.

        :param request: The request object to send.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = operations.CREATE_POLICY_SERVERS[0]

        if not isinstance(request, BaseModel):
            request = utils.unmarshal(request, reconciliation.PolicyRequest)
        request = cast(reconciliation.PolicyRequest, request)

        req = self._build_request_async(
            method="POST",
            path="/api/reconciliation/policies",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request, False, False, "json", reconciliation.PolicyRequest
            ),
            allow_empty_value=None,
            allowed_fields=["client_id"],
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="createPolicy",
                oauth2_scopes=["reconciliation:write"],
                security_source=self.sdk_configuration.security,
            ),
            request=req,
            is_error_status_code=lambda c: not utils.match_status_codes(["201"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "201", "application/json"):
            return operations.CreatePolicyResponse(
                policy_response=unmarshal_json_response(
                    Optional[reconciliation.PolicyResponse], http_res
                ),
                status_code=http_res.status_code,
                content_type=http_res.headers.get("Content-Type") or "",
                raw_response=http_res,
            )
        if utils.match_response(http_res, "default", "application/json"):
            response_data = unmarshal_json_response(
                reconciliation.ErrorResponseData, http_res
            )
            raise reconciliation.ErrorResponse(response_data, http_res)

        raise errors.SDKError("Unexpected response received", http_res)

    def delete_policy(
        self,
        *,
        request: Union[
            operations.DeletePolicyRequest, operations.DeletePolicyRequestTypedDict
        ],
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> operations.DeletePolicyResponse:
        r"""Delete a policy

        Delete a policy by its id.

        If set, this operation will use `client_id` from the global security.

        :param request: The request object to send.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = operations.DELETE_POLICY_SERVERS[0]

        if not isinstance(request, BaseModel):
            request = utils.unmarshal(request, operations.DeletePolicyRequest)
        request = cast(operations.DeletePolicyRequest, request)

        req = self._build_request(
            method="DELETE",
            path="/api/reconciliation/policies/{policyID}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            allowed_fields=["client_id"],
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="deletePolicy",
                oauth2_scopes=["reconciliation:write"],
                security_source=self.sdk_configuration.security,
            ),
            request=req,
            is_error_status_code=lambda c: not utils.match_status_codes(["204"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "204", "*"):
            return operations.DeletePolicyResponse(
                status_code=http_res.status_code,
                content_type=http_res.headers.get("Content-Type") or "",
                raw_response=http_res,
            )
        if utils.match_response(http_res, "default", "application/json"):
            response_data = unmarshal_json_response(
                reconciliation.ErrorResponseData, http_res
            )
            raise reconciliation.ErrorResponse(response_data, http_res)

        raise errors.SDKError("Unexpected response received", http_res)

    async def delete_policy_async(
        self,
        *,
        request: Union[
            operations.DeletePolicyRequest, operations.DeletePolicyRequestTypedDict
        ],
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> operations.DeletePolicyResponse:
        r"""Delete a policy

        Delete a policy by its id.

        If set, this operation will use `client_id` from the global security.

        :param request: The request object to send.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = operations.DELETE_POLICY_SERVERS[0]

        if not isinstance(request, BaseModel):
            request = utils.unmarshal(request, operations.DeletePolicyRequest)
        request = cast(operations.DeletePolicyRequest, request)

        req = self._build_request_async(
            method="DELETE",
            path="/api/reconciliation/policies/{policyID}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            allowed_fields=["client_id"],
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="deletePolicy",
                oauth2_scopes=["reconciliation:write"],
                security_source=self.sdk_configuration.security,
            ),
            request=req,
            is_error_status_code=lambda c: not utils.match_status_codes(["204"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "204", "*"):
            return operations.DeletePolicyResponse(
                status_code=http_res.status_code,
                content_type=http_res.headers.get("Content-Type") or "",
                raw_response=http_res,
            )
        if utils.match_response(http_res, "default", "application/json"):
            response_data = unmarshal_json_response(
                reconciliation.ErrorResponseData, http_res
            )
            raise reconciliation.ErrorResponse(response_data, http_res)

        raise errors.SDKError("Unexpected response received", http_res)

    def get_policy(
        self,
        *,
        request: Union[
            operations.GetPolicyRequest, operations.GetPolicyRequestTypedDict
        ],
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> operations.GetPolicyResponse:
        r"""Get a policy

        If set, this operation will use `client_id` from the global security.

        :param request: The request object to send.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = operations.GET_POLICY_SERVERS[0]

        if not isinstance(request, BaseModel):
            request = utils.unmarshal(request, operations.GetPolicyRequest)
        request = cast(operations.GetPolicyRequest, request)

        req = self._build_request(
            method="GET",
            path="/api/reconciliation/policies/{policyID}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            allowed_fields=["client_id"],
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="getPolicy",
                oauth2_scopes=["reconciliation:read"],
                security_source=self.sdk_configuration.security,
            ),
            request=req,
            is_error_status_code=lambda c: not utils.match_status_codes(["200"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return operations.GetPolicyResponse(
                policy_response=unmarshal_json_response(
                    Optional[reconciliation.PolicyResponse], http_res
                ),
                status_code=http_res.status_code,
                content_type=http_res.headers.get("Content-Type") or "",
                raw_response=http_res,
            )
        if utils.match_response(http_res, "default", "application/json"):
            response_data = unmarshal_json_response(
                reconciliation.ErrorResponseData, http_res
            )
            raise reconciliation.ErrorResponse(response_data, http_res)

        raise errors.SDKError("Unexpected response received", http_res)

    async def get_policy_async(
        self,
        *,
        request: Union[
            operations.GetPolicyRequest, operations.GetPolicyRequestTypedDict
        ],
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> operations.GetPolicyResponse:
        r"""Get a policy

        If set, this operation will use `client_id` from the global security.

        :param request: The request object to send.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = operations.GET_POLICY_SERVERS[0]

        if not isinstance(request, BaseModel):
            request = utils.unmarshal(request, operations.GetPolicyRequest)
        request = cast(operations.GetPolicyRequest, request)

        req = self._build_request_async(
            method="GET",
            path="/api/reconciliation/policies/{policyID}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            allowed_fields=["client_id"],
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="getPolicy",
                oauth2_scopes=["reconciliation:read"],
                security_source=self.sdk_configuration.security,
            ),
            request=req,
            is_error_status_code=lambda c: not utils.match_status_codes(["200"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return operations.GetPolicyResponse(
                policy_response=unmarshal_json_response(
                    Optional[reconciliation.PolicyResponse], http_res
                ),
                status_code=http_res.status_code,
                content_type=http_res.headers.get("Content-Type") or "",
                raw_response=http_res,
            )
        if utils.match_response(http_res, "default", "application/json"):
            response_data = unmarshal_json_response(
                reconciliation.ErrorResponseData, http_res
            )
            raise reconciliation.ErrorResponse(response_data, http_res)

        raise errors.SDKError("Unexpected response received", http_res)

    def get_reconciliation(
        self,
        *,
        request: Union[
            operations.GetReconciliationRequest,
            operations.GetReconciliationRequestTypedDict,
        ],
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> operations.GetReconciliationResponse:
        r"""Get a reconciliation

        If set, this operation will use `client_id` from the global security.

        :param request: The request object to send.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = operations.GET_RECONCILIATION_SERVERS[0]

        if not isinstance(request, BaseModel):
            request = utils.unmarshal(request, operations.GetReconciliationRequest)
        request = cast(operations.GetReconciliationRequest, request)

        req = self._build_request(
            method="GET",
            path="/api/reconciliation/reconciliations/{reconciliationID}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            allowed_fields=["client_id"],
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="getReconciliation",
                oauth2_scopes=["reconciliation:read"],
                security_source=self.sdk_configuration.security,
            ),
            request=req,
            is_error_status_code=lambda c: not utils.match_status_codes(["200"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return operations.GetReconciliationResponse(
                reconciliation_response=unmarshal_json_response(
                    Optional[reconciliation.ReconciliationResponse], http_res
                ),
                status_code=http_res.status_code,
                content_type=http_res.headers.get("Content-Type") or "",
                raw_response=http_res,
            )
        if utils.match_response(http_res, "default", "application/json"):
            response_data = unmarshal_json_response(
                reconciliation.ErrorResponseData, http_res
            )
            raise reconciliation.ErrorResponse(response_data, http_res)

        raise errors.SDKError("Unexpected response received", http_res)

    async def get_reconciliation_async(
        self,
        *,
        request: Union[
            operations.GetReconciliationRequest,
            operations.GetReconciliationRequestTypedDict,
        ],
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> operations.GetReconciliationResponse:
        r"""Get a reconciliation

        If set, this operation will use `client_id` from the global security.

        :param request: The request object to send.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = operations.GET_RECONCILIATION_SERVERS[0]

        if not isinstance(request, BaseModel):
            request = utils.unmarshal(request, operations.GetReconciliationRequest)
        request = cast(operations.GetReconciliationRequest, request)

        req = self._build_request_async(
            method="GET",
            path="/api/reconciliation/reconciliations/{reconciliationID}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            allowed_fields=["client_id"],
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="getReconciliation",
                oauth2_scopes=["reconciliation:read"],
                security_source=self.sdk_configuration.security,
            ),
            request=req,
            is_error_status_code=lambda c: not utils.match_status_codes(["200"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return operations.GetReconciliationResponse(
                reconciliation_response=unmarshal_json_response(
                    Optional[reconciliation.ReconciliationResponse], http_res
                ),
                status_code=http_res.status_code,
                content_type=http_res.headers.get("Content-Type") or "",
                raw_response=http_res,
            )
        if utils.match_response(http_res, "default", "application/json"):
            response_data = unmarshal_json_response(
                reconciliation.ErrorResponseData, http_res
            )
            raise reconciliation.ErrorResponse(response_data, http_res)

        raise errors.SDKError("Unexpected response received", http_res)

    def get_server_info_reconciliation(
        self,
        *,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> operations.GetServerInfoReconciliationResponse:
        r"""Get server info

        If set, this operation will use `client_id` from the global security.

        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = operations.GET_SERVER_INFO_RECONCILIATION_SERVERS[0]
        req = self._build_request(
            method="GET",
            path="/api/reconciliation/_info",
            base_url=base_url,
            url_variables=url_variables,
            request=None,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            allowed_fields=["client_id"],
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="getServerInfo_reconciliation",
                oauth2_scopes=["reconciliation:read"],
                security_source=self.sdk_configuration.security,
            ),
            request=req,
            is_error_status_code=lambda c: not utils.match_status_codes(["200"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return operations.GetServerInfoReconciliationResponse(
                server_info=unmarshal_json_response(
                    Optional[reconciliation.ServerInfo], http_res
                ),
                status_code=http_res.status_code,
                content_type=http_res.headers.get("Content-Type") or "",
                raw_response=http_res,
            )
        if utils.match_response(http_res, "default", "application/json"):
            response_data = unmarshal_json_response(
                reconciliation.ErrorResponseData, http_res
            )
            raise reconciliation.ErrorResponse(response_data, http_res)

        raise errors.SDKError("Unexpected response received", http_res)

    async def get_server_info_reconciliation_async(
        self,
        *,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> operations.GetServerInfoReconciliationResponse:
        r"""Get server info

        If set, this operation will use `client_id` from the global security.

        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = operations.GET_SERVER_INFO_RECONCILIATION_SERVERS[0]
        req = self._build_request_async(
            method="GET",
            path="/api/reconciliation/_info",
            base_url=base_url,
            url_variables=url_variables,
            request=None,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            allowed_fields=["client_id"],
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="getServerInfo_reconciliation",
                oauth2_scopes=["reconciliation:read"],
                security_source=self.sdk_configuration.security,
            ),
            request=req,
            is_error_status_code=lambda c: not utils.match_status_codes(["200"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return operations.GetServerInfoReconciliationResponse(
                server_info=unmarshal_json_response(
                    Optional[reconciliation.ServerInfo], http_res
                ),
                status_code=http_res.status_code,
                content_type=http_res.headers.get("Content-Type") or "",
                raw_response=http_res,
            )
        if utils.match_response(http_res, "default", "application/json"):
            response_data = unmarshal_json_response(
                reconciliation.ErrorResponseData, http_res
            )
            raise reconciliation.ErrorResponse(response_data, http_res)

        raise errors.SDKError("Unexpected response received", http_res)

    def list_policies(
        self,
        *,
        request: Union[
            operations.ListPoliciesRequest, operations.ListPoliciesRequestTypedDict
        ],
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> operations.ListPoliciesResponse:
        r"""List policies

        If set, this operation will use `client_id` from the global security.

        :param request: The request object to send.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = operations.LIST_POLICIES_SERVERS[0]

        if not isinstance(request, BaseModel):
            request = utils.unmarshal(request, operations.ListPoliciesRequest)
        request = cast(operations.ListPoliciesRequest, request)

        req = self._build_request(
            method="GET",
            path="/api/reconciliation/policies",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.request_body if request is not None else None,
                False,
                True,
                "json",
                Optional[Dict[str, Any]],
            ),
            allow_empty_value=None,
            allowed_fields=["client_id"],
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="listPolicies",
                oauth2_scopes=["reconciliation:read"],
                security_source=self.sdk_configuration.security,
            ),
            request=req,
            is_error_status_code=lambda c: not utils.match_status_codes(["200"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return operations.ListPoliciesResponse(
                policies_cursor_response=unmarshal_json_response(
                    Optional[reconciliation.PoliciesCursorResponse], http_res
                ),
                status_code=http_res.status_code,
                content_type=http_res.headers.get("Content-Type") or "",
                raw_response=http_res,
            )
        if utils.match_response(http_res, "default", "application/json"):
            response_data = unmarshal_json_response(
                reconciliation.ErrorResponseData, http_res
            )
            raise reconciliation.ErrorResponse(response_data, http_res)

        raise errors.SDKError("Unexpected response received", http_res)

    async def list_policies_async(
        self,
        *,
        request: Union[
            operations.ListPoliciesRequest, operations.ListPoliciesRequestTypedDict
        ],
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> operations.ListPoliciesResponse:
        r"""List policies

        If set, this operation will use `client_id` from the global security.

        :param request: The request object to send.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = operations.LIST_POLICIES_SERVERS[0]

        if not isinstance(request, BaseModel):
            request = utils.unmarshal(request, operations.ListPoliciesRequest)
        request = cast(operations.ListPoliciesRequest, request)

        req = self._build_request_async(
            method="GET",
            path="/api/reconciliation/policies",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.request_body if request is not None else None,
                False,
                True,
                "json",
                Optional[Dict[str, Any]],
            ),
            allow_empty_value=None,
            allowed_fields=["client_id"],
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="listPolicies",
                oauth2_scopes=["reconciliation:read"],
                security_source=self.sdk_configuration.security,
            ),
            request=req,
            is_error_status_code=lambda c: not utils.match_status_codes(["200"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return operations.ListPoliciesResponse(
                policies_cursor_response=unmarshal_json_response(
                    Optional[reconciliation.PoliciesCursorResponse], http_res
                ),
                status_code=http_res.status_code,
                content_type=http_res.headers.get("Content-Type") or "",
                raw_response=http_res,
            )
        if utils.match_response(http_res, "default", "application/json"):
            response_data = unmarshal_json_response(
                reconciliation.ErrorResponseData, http_res
            )
            raise reconciliation.ErrorResponse(response_data, http_res)

        raise errors.SDKError("Unexpected response received", http_res)

    def list_reconciliations(
        self,
        *,
        request: Union[
            operations.ListReconciliationsRequest,
            operations.ListReconciliationsRequestTypedDict,
        ],
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> operations.ListReconciliationsResponse:
        r"""List reconciliations

        If set, this operation will use `client_id` from the global security.

        :param request: The request object to send.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = operations.LIST_RECONCILIATIONS_SERVERS[0]

        if not isinstance(request, BaseModel):
            request = utils.unmarshal(request, operations.ListReconciliationsRequest)
        request = cast(operations.ListReconciliationsRequest, request)

        req = self._build_request(
            method="GET",
            path="/api/reconciliation/reconciliations",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.request_body if request is not None else None,
                False,
                True,
                "json",
                Optional[Dict[str, Any]],
            ),
            allow_empty_value=None,
            allowed_fields=["client_id"],
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="listReconciliations",
                oauth2_scopes=["reconciliation:read"],
                security_source=self.sdk_configuration.security,
            ),
            request=req,
            is_error_status_code=lambda c: not utils.match_status_codes(["200"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return operations.ListReconciliationsResponse(
                reconciliations_cursor_response=unmarshal_json_response(
                    Optional[reconciliation.ReconciliationsCursorResponse], http_res
                ),
                status_code=http_res.status_code,
                content_type=http_res.headers.get("Content-Type") or "",
                raw_response=http_res,
            )
        if utils.match_response(http_res, "default", "application/json"):
            response_data = unmarshal_json_response(
                reconciliation.ErrorResponseData, http_res
            )
            raise reconciliation.ErrorResponse(response_data, http_res)

        raise errors.SDKError("Unexpected response received", http_res)

    async def list_reconciliations_async(
        self,
        *,
        request: Union[
            operations.ListReconciliationsRequest,
            operations.ListReconciliationsRequestTypedDict,
        ],
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> operations.ListReconciliationsResponse:
        r"""List reconciliations

        If set, this operation will use `client_id` from the global security.

        :param request: The request object to send.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = operations.LIST_RECONCILIATIONS_SERVERS[0]

        if not isinstance(request, BaseModel):
            request = utils.unmarshal(request, operations.ListReconciliationsRequest)
        request = cast(operations.ListReconciliationsRequest, request)

        req = self._build_request_async(
            method="GET",
            path="/api/reconciliation/reconciliations",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.request_body if request is not None else None,
                False,
                True,
                "json",
                Optional[Dict[str, Any]],
            ),
            allow_empty_value=None,
            allowed_fields=["client_id"],
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="listReconciliations",
                oauth2_scopes=["reconciliation:read"],
                security_source=self.sdk_configuration.security,
            ),
            request=req,
            is_error_status_code=lambda c: not utils.match_status_codes(["200"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return operations.ListReconciliationsResponse(
                reconciliations_cursor_response=unmarshal_json_response(
                    Optional[reconciliation.ReconciliationsCursorResponse], http_res
                ),
                status_code=http_res.status_code,
                content_type=http_res.headers.get("Content-Type") or "",
                raw_response=http_res,
            )
        if utils.match_response(http_res, "default", "application/json"):
            response_data = unmarshal_json_response(
                reconciliation.ErrorResponseData, http_res
            )
            raise reconciliation.ErrorResponse(response_data, http_res)

        raise errors.SDKError("Unexpected response received", http_res)

    def reconcile(
        self,
        *,
        request: Union[
            operations.ReconcileRequest, operations.ReconcileRequestTypedDict
        ],
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> operations.ReconcileResponse:
        r"""Reconcile using a policy

        Reconcile using a policy

        If set, this operation will use `client_id` from the global security.

        :param request: The request object to send.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = operations.RECONCILE_SERVERS[0]

        if not isinstance(request, BaseModel):
            request = utils.unmarshal(request, operations.ReconcileRequest)
        request = cast(operations.ReconcileRequest, request)

        req = self._build_request(
            method="POST",
            path="/api/reconciliation/policies/{policyID}/reconciliation",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.reconciliation_request,
                False,
                False,
                "json",
                reconciliation.ReconciliationRequest,
            ),
            allow_empty_value=None,
            allowed_fields=["client_id"],
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="reconcile",
                oauth2_scopes=["reconciliation:write"],
                security_source=self.sdk_configuration.security,
            ),
            request=req,
            is_error_status_code=lambda c: not utils.match_status_codes(["200"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return operations.ReconcileResponse(
                reconciliation_response=unmarshal_json_response(
                    Optional[reconciliation.ReconciliationResponse], http_res
                ),
                status_code=http_res.status_code,
                content_type=http_res.headers.get("Content-Type") or "",
                raw_response=http_res,
            )
        if utils.match_response(http_res, "default", "application/json"):
            response_data = unmarshal_json_response(
                reconciliation.ErrorResponseData, http_res
            )
            raise reconciliation.ErrorResponse(response_data, http_res)

        raise errors.SDKError("Unexpected response received", http_res)

    async def reconcile_async(
        self,
        *,
        request: Union[
            operations.ReconcileRequest, operations.ReconcileRequestTypedDict
        ],
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> operations.ReconcileResponse:
        r"""Reconcile using a policy

        Reconcile using a policy

        If set, this operation will use `client_id` from the global security.

        :param request: The request object to send.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = operations.RECONCILE_SERVERS[0]

        if not isinstance(request, BaseModel):
            request = utils.unmarshal(request, operations.ReconcileRequest)
        request = cast(operations.ReconcileRequest, request)

        req = self._build_request_async(
            method="POST",
            path="/api/reconciliation/policies/{policyID}/reconciliation",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.reconciliation_request,
                False,
                False,
                "json",
                reconciliation.ReconciliationRequest,
            ),
            allow_empty_value=None,
            allowed_fields=["client_id"],
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="reconcile",
                oauth2_scopes=["reconciliation:write"],
                security_source=self.sdk_configuration.security,
            ),
            request=req,
            is_error_status_code=lambda c: not utils.match_status_codes(["200"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return operations.ReconcileResponse(
                reconciliation_response=unmarshal_json_response(
                    Optional[reconciliation.ReconciliationResponse], http_res
                ),
                status_code=http_res.status_code,
                content_type=http_res.headers.get("Content-Type") or "",
                raw_response=http_res,
            )
        if utils.match_response(http_res, "default", "application/json"):
            response_data = unmarshal_json_response(
                reconciliation.ErrorResponseData, http_res
            )
            raise reconciliation.ErrorResponse(response_data, http_res)

        raise errors.SDKError("Unexpected response received", http_res)
