"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import Any, TYPE_CHECKING

from formance_sdk_python.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .clientoptions_1 import ClientOptions1, ClientOptions1TypedDict
    from .clientoptions_2 import ClientOptions2, ClientOptions2TypedDict
    from .clientsecret import ClientSecret, ClientSecretTypedDict
    from .createclientresponse import (
        CreateClientResponse,
        CreateClientResponseTypedDict,
    )
    from .createsecretresponse import (
        CreateSecretResponse,
        CreateSecretResponseTypedDict,
    )
    from .listclientsresponse import ListClientsResponse, ListClientsResponseTypedDict
    from .listusersresponse import ListUsersResponse, ListUsersResponseTypedDict
    from .readclientresponse import ReadClientResponse, ReadClientResponseTypedDict
    from .readuserresponse import ReadUserResponse, ReadUserResponseTypedDict
    from .secretoptions_1 import SecretOptions1, SecretOptions1TypedDict
    from .secretoptions_2 import SecretOptions2, SecretOptions2TypedDict
    from .serverinfo import ServerInfo, ServerInfoTypedDict
    from .user import User, UserTypedDict

__all__ = [
    "ClientOptions1",
    "ClientOptions1TypedDict",
    "ClientOptions2",
    "ClientOptions2TypedDict",
    "ClientSecret",
    "ClientSecretTypedDict",
    "CreateClientResponse",
    "CreateClientResponseTypedDict",
    "CreateSecretResponse",
    "CreateSecretResponseTypedDict",
    "ListClientsResponse",
    "ListClientsResponseTypedDict",
    "ListUsersResponse",
    "ListUsersResponseTypedDict",
    "ReadClientResponse",
    "ReadClientResponseTypedDict",
    "ReadUserResponse",
    "ReadUserResponseTypedDict",
    "SecretOptions1",
    "SecretOptions1TypedDict",
    "SecretOptions2",
    "SecretOptions2TypedDict",
    "ServerInfo",
    "ServerInfoTypedDict",
    "User",
    "UserTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "ClientOptions1": ".clientoptions_1",
    "ClientOptions1TypedDict": ".clientoptions_1",
    "ClientOptions2": ".clientoptions_2",
    "ClientOptions2TypedDict": ".clientoptions_2",
    "ClientSecret": ".clientsecret",
    "ClientSecretTypedDict": ".clientsecret",
    "CreateClientResponse": ".createclientresponse",
    "CreateClientResponseTypedDict": ".createclientresponse",
    "CreateSecretResponse": ".createsecretresponse",
    "CreateSecretResponseTypedDict": ".createsecretresponse",
    "ListClientsResponse": ".listclientsresponse",
    "ListClientsResponseTypedDict": ".listclientsresponse",
    "ListUsersResponse": ".listusersresponse",
    "ListUsersResponseTypedDict": ".listusersresponse",
    "ReadClientResponse": ".readclientresponse",
    "ReadClientResponseTypedDict": ".readclientresponse",
    "ReadUserResponse": ".readuserresponse",
    "ReadUserResponseTypedDict": ".readuserresponse",
    "SecretOptions1": ".secretoptions_1",
    "SecretOptions1TypedDict": ".secretoptions_1",
    "SecretOptions2": ".secretoptions_2",
    "SecretOptions2TypedDict": ".secretoptions_2",
    "ServerInfo": ".serverinfo",
    "ServerInfoTypedDict": ".serverinfo",
    "User": ".user",
    "UserTypedDict": ".user",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
