"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .secretoptions_2 import SecretOptions2, SecretOptions2TypedDict
from formance_sdk_python.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CreateSecretResponseTypedDict(TypedDict):
    secret_options: NotRequired[SecretOptions2TypedDict]


class CreateSecretResponse(BaseModel):
    secret_options: Annotated[
        Optional[SecretOptions2], pydantic.Field(alias="data")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["SecretOptions"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    CreateSecretResponse.model_rebuild()
except NameError:
    pass
