workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    stacks-source:
        inputs:
            - location: https://github.com/formancehq/stack/releases/download/v3.0.5/generate.json
        registry:
            location: registry.speakeasyapi.dev/formance/formance/stacks-source
targets:
    formance-python-sdk:
        target: python
        source: stacks-source
        publish:
            pypi:
                token: $PYPI_TOKEN
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/formance/formance/stacks-source-python-code-samples
            labelOverride:
                fixedValue: Python (SDK)
            blocking: false
