workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    my-source:
        inputs:
            - location: https://github.com/formancehq/stack/releases/download/v2.1.1/generate.json
        registry:
            location: registry.speakeasyapi.dev/formance/formance/my-source
targets:
    formance-python-sdk:
        target: python
        source: my-source
        publish:
            pypi:
                token: $PYPI_TOKEN
