"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .migrationinfo import MigrationInfo, MigrationInfoTypedDict
from formance_sdk_python.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class LedgerInfoStorageTypedDict(TypedDict):
    migrations: NotRequired[List[MigrationInfoTypedDict]]


class LedgerInfoStorage(BaseModel):
    migrations: Optional[List[MigrationInfo]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["migrations"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class LedgerInfoTypedDict(TypedDict):
    name: NotRequired[str]
    storage: NotRequired[LedgerInfoStorageTypedDict]


class LedgerInfo(BaseModel):
    name: Optional[str] = None

    storage: Optional[LedgerInfoStorage] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["name", "storage"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
