"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .posting import Posting, PostingTypedDict
from datetime import datetime
from formance_sdk_python.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import Any, Dict, List, Optional
from typing_extensions import NotRequired, TypedDict


class PostTransactionScriptTypedDict(TypedDict):
    plain: str
    vars: NotRequired[Dict[str, Any]]


class PostTransactionScript(BaseModel):
    plain: str

    vars: Optional[Dict[str, Any]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["vars"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class PostTransactionTypedDict(TypedDict):
    metadata: NotRequired[Nullable[Dict[str, Any]]]
    postings: NotRequired[List[PostingTypedDict]]
    reference: NotRequired[str]
    script: NotRequired[PostTransactionScriptTypedDict]
    timestamp: NotRequired[datetime]


class PostTransaction(BaseModel):
    metadata: OptionalNullable[Dict[str, Any]] = UNSET

    postings: Optional[List[Posting]] = None

    reference: Optional[str] = None

    script: Optional[PostTransactionScript] = None

    timestamp: Optional[datetime] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["Metadata", "postings", "reference", "script", "timestamp"]
        )
        nullable_fields = set(["Metadata"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
