"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .v2pipelineconfiguration import (
    V2PipelineConfiguration,
    V2PipelineConfigurationTypedDict,
)
from formance_sdk_python.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class V2CreatePipelineResponseTypedDict(TypedDict):
    r"""Created ipeline"""

    v2_pipeline_configuration: V2PipelineConfigurationTypedDict


class V2CreatePipelineResponse(BaseModel):
    r"""Created ipeline"""

    v2_pipeline_configuration: Annotated[
        V2PipelineConfiguration, pydantic.Field(alias="data")
    ]


try:
    V2CreatePipelineResponse.model_rebuild()
except NameError:
    pass
