"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from formance_sdk_python.types import BaseModel
from formance_sdk_python.utils import validate_int
import pydantic
from pydantic.functional_validators import BeforeValidator
from typing import Dict, Union
from typing_extensions import Annotated, TypeAliasType, TypedDict


V2LogDataSetMetadataTargetIDTypedDict = TypeAliasType(
    "V2LogDataSetMetadataTargetIDTypedDict", Union[str, int]
)


V2LogDataSetMetadataTargetID = TypeAliasType(
    "V2LogDataSetMetadataTargetID",
    Union[str, Annotated[int, BeforeValidator(validate_int)]],
)


class V2LogDataSetMetadataTargetType(str, Enum):
    r"""Type of the target entity"""

    ACCOUNT = "ACCOUNT"
    TRANSACTION = "TRANSACTION"


class V2LogDataSetMetadataTypedDict(TypedDict):
    r"""Payload for SET_METADATA log entries. Contains the target entity and the metadata that was set."""

    v2_metadata: Dict[str, str]
    target_id: V2LogDataSetMetadataTargetIDTypedDict
    target_type: V2LogDataSetMetadataTargetType
    r"""Type of the target entity"""


class V2LogDataSetMetadata(BaseModel):
    r"""Payload for SET_METADATA log entries. Contains the target entity and the metadata that was set."""

    v2_metadata: Annotated[Dict[str, str], pydantic.Field(alias="metadata")]

    target_id: Annotated[V2LogDataSetMetadataTargetID, pydantic.Field(alias="targetId")]

    target_type: Annotated[
        V2LogDataSetMetadataTargetType, pydantic.Field(alias="targetType")
    ]
    r"""Type of the target entity"""


try:
    V2LogDataSetMetadata.model_rebuild()
except NameError:
    pass
