"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from enum import Enum
from formance_sdk_python.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class V2QueryParamsResourceVolumes(str, Enum):
    VOLUMES = "volumes"


class QueryTemplateVolumeParamsTypedDict(TypedDict):
    cursor: NotRequired[str]
    r"""Parameter used in pagination requests. Maximum page size is set to 15.
    Set to the value of next for the next page of results.
    Set to the value of previous for the previous page of results.
    No other parameters can be set when this parameter is set.

    """
    expand: NotRequired[str]
    group_by: NotRequired[int]
    insertion_date: NotRequired[bool]
    page_size: NotRequired[int]
    r"""The maximum number of results to return per page.

    """
    pit: NotRequired[datetime]
    resource: NotRequired[V2QueryParamsResourceVolumes]
    sort: NotRequired[str]
    r"""Sort results using a field name and order (ascending or descending).
    Format: `<field>:<order>`, where `<field>` is the field name and `<order>` is either `asc` or `desc`.

    """


class QueryTemplateVolumeParams(BaseModel):
    cursor: Optional[str] = None
    r"""Parameter used in pagination requests. Maximum page size is set to 15.
    Set to the value of next for the next page of results.
    Set to the value of previous for the previous page of results.
    No other parameters can be set when this parameter is set.

    """

    expand: Optional[str] = None

    group_by: Annotated[Optional[int], pydantic.Field(alias="groupBy")] = None

    insertion_date: Annotated[Optional[bool], pydantic.Field(alias="insertionDate")] = (
        None
    )

    page_size: Annotated[Optional[int], pydantic.Field(alias="pageSize")] = None
    r"""The maximum number of results to return per page.

    """

    pit: Optional[datetime] = None

    resource: Optional[V2QueryParamsResourceVolumes] = None

    sort: Optional[str] = None
    r"""Sort results using a field name and order (ascending or descending).
    Format: `<field>:<order>`, where `<field>` is the field name and `<order>` is either `asc` or `desc`.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "cursor",
                "expand",
                "groupBy",
                "insertionDate",
                "pageSize",
                "pit",
                "resource",
                "sort",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class V2QueryParamsResourceLogs(str, Enum):
    LOGS = "logs"


class QueryTemplateLogParamsTypedDict(TypedDict):
    cursor: NotRequired[str]
    r"""Parameter used in pagination requests. Maximum page size is set to 15.
    Set to the value of next for the next page of results.
    Set to the value of previous for the previous page of results.
    No other parameters can be set when this parameter is set.

    """
    expand: NotRequired[str]
    page_size: NotRequired[int]
    r"""The maximum number of results to return per page.

    """
    pit: NotRequired[datetime]
    resource: NotRequired[V2QueryParamsResourceLogs]
    sort: NotRequired[str]
    r"""Sort results using a field name and order (ascending or descending).
    Format: `<field>:<order>`, where `<field>` is the field name and `<order>` is either `asc` or `desc`.

    """


class QueryTemplateLogParams(BaseModel):
    cursor: Optional[str] = None
    r"""Parameter used in pagination requests. Maximum page size is set to 15.
    Set to the value of next for the next page of results.
    Set to the value of previous for the previous page of results.
    No other parameters can be set when this parameter is set.

    """

    expand: Optional[str] = None

    page_size: Annotated[Optional[int], pydantic.Field(alias="pageSize")] = None
    r"""The maximum number of results to return per page.

    """

    pit: Optional[datetime] = None

    resource: Optional[V2QueryParamsResourceLogs] = None

    sort: Optional[str] = None
    r"""Sort results using a field name and order (ascending or descending).
    Format: `<field>:<order>`, where `<field>` is the field name and `<order>` is either `asc` or `desc`.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["cursor", "expand", "pageSize", "pit", "resource", "sort"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class V2QueryParamsResourceTransactions(str, Enum):
    TRANSACTIONS = "transactions"


class QueryTemplateTransactionParamsTypedDict(TypedDict):
    cursor: NotRequired[str]
    r"""Parameter used in pagination requests. Maximum page size is set to 15.
    Set to the value of next for the next page of results.
    Set to the value of previous for the previous page of results.
    No other parameters can be set when this parameter is set.

    """
    expand: NotRequired[str]
    page_size: NotRequired[int]
    r"""The maximum number of results to return per page.

    """
    pit: NotRequired[datetime]
    resource: NotRequired[V2QueryParamsResourceTransactions]
    sort: NotRequired[str]
    r"""Sort results using a field name and order (ascending or descending).
    Format: `<field>:<order>`, where `<field>` is the field name and `<order>` is either `asc` or `desc`.

    """


class QueryTemplateTransactionParams(BaseModel):
    cursor: Optional[str] = None
    r"""Parameter used in pagination requests. Maximum page size is set to 15.
    Set to the value of next for the next page of results.
    Set to the value of previous for the previous page of results.
    No other parameters can be set when this parameter is set.

    """

    expand: Optional[str] = None

    page_size: Annotated[Optional[int], pydantic.Field(alias="pageSize")] = None
    r"""The maximum number of results to return per page.

    """

    pit: Optional[datetime] = None

    resource: Optional[V2QueryParamsResourceTransactions] = None

    sort: Optional[str] = None
    r"""Sort results using a field name and order (ascending or descending).
    Format: `<field>:<order>`, where `<field>` is the field name and `<order>` is either `asc` or `desc`.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["cursor", "expand", "pageSize", "pit", "resource", "sort"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class V2QueryParamsResourceAccounts(str, Enum):
    ACCOUNTS = "accounts"


class QueryTemplateAccountParamsTypedDict(TypedDict):
    cursor: NotRequired[str]
    r"""Parameter used in pagination requests. Maximum page size is set to 15.
    Set to the value of next for the next page of results.
    Set to the value of previous for the previous page of results.
    No other parameters can be set when this parameter is set.

    """
    expand: NotRequired[str]
    page_size: NotRequired[int]
    r"""The maximum number of results to return per page.

    """
    pit: NotRequired[datetime]
    resource: NotRequired[V2QueryParamsResourceAccounts]
    sort: NotRequired[str]
    r"""Sort results using a field name and order (ascending or descending).
    Format: `<field>:<order>`, where `<field>` is the field name and `<order>` is either `asc` or `desc`.

    """


class QueryTemplateAccountParams(BaseModel):
    cursor: Optional[str] = None
    r"""Parameter used in pagination requests. Maximum page size is set to 15.
    Set to the value of next for the next page of results.
    Set to the value of previous for the previous page of results.
    No other parameters can be set when this parameter is set.

    """

    expand: Optional[str] = None

    page_size: Annotated[Optional[int], pydantic.Field(alias="pageSize")] = None
    r"""The maximum number of results to return per page.

    """

    pit: Optional[datetime] = None

    resource: Optional[V2QueryParamsResourceAccounts] = None

    sort: Optional[str] = None
    r"""Sort results using a field name and order (ascending or descending).
    Format: `<field>:<order>`, where `<field>` is the field name and `<order>` is either `asc` or `desc`.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["cursor", "expand", "pageSize", "pit", "resource", "sort"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


V2QueryParamsTypedDict = TypeAliasType(
    "V2QueryParamsTypedDict",
    Union[
        QueryTemplateAccountParamsTypedDict,
        QueryTemplateTransactionParamsTypedDict,
        QueryTemplateLogParamsTypedDict,
        QueryTemplateVolumeParamsTypedDict,
    ],
)


V2QueryParams = TypeAliasType(
    "V2QueryParams",
    Union[
        QueryTemplateAccountParams,
        QueryTemplateTransactionParams,
        QueryTemplateLogParams,
        QueryTemplateVolumeParams,
    ],
)


try:
    QueryTemplateVolumeParams.model_rebuild()
except NameError:
    pass
try:
    QueryTemplateLogParams.model_rebuild()
except NameError:
    pass
try:
    QueryTemplateTransactionParams.model_rebuild()
except NameError:
    pass
try:
    QueryTemplateAccountParams.model_rebuild()
except NameError:
    pass
