"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .v2chartsegment import V2ChartSegment, V2ChartSegmentTypedDict
from .v2querytemplate import V2QueryTemplate, V2QueryTemplateTypedDict
from .v2transactiontemplate import V2TransactionTemplate, V2TransactionTemplateTypedDict
from datetime import datetime
from formance_sdk_python.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Dict, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class V2SchemaData1TypedDict(TypedDict):
    r"""Complete schema structure with metadata"""

    v2_chart_of_accounts: Dict[str, V2ChartSegmentTypedDict]
    r"""Chart of account"""
    created_at: datetime
    r"""Schema creation timestamp"""
    version: str
    r"""Schema version"""
    v2_query_templates: NotRequired[Dict[str, V2QueryTemplateTypedDict]]
    r"""Query templates"""
    v2_transaction_templates: NotRequired[Dict[str, V2TransactionTemplateTypedDict]]
    r"""Transaction templates"""


class V2SchemaData1(BaseModel):
    r"""Complete schema structure with metadata"""

    v2_chart_of_accounts: Annotated[
        Dict[str, V2ChartSegment], pydantic.Field(alias="chart")
    ]
    r"""Chart of account"""

    created_at: Annotated[datetime, pydantic.Field(alias="createdAt")]
    r"""Schema creation timestamp"""

    version: str
    r"""Schema version"""

    v2_query_templates: Annotated[
        Optional[Dict[str, V2QueryTemplate]], pydantic.Field(alias="queries")
    ] = None
    r"""Query templates"""

    v2_transaction_templates: Annotated[
        Optional[Dict[str, V2TransactionTemplate]], pydantic.Field(alias="transactions")
    ] = None
    r"""Transaction templates"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["V2QueryTemplates", "V2TransactionTemplates"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    V2SchemaData1.model_rebuild()
except NameError:
    pass
