"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .v2stats import V2Stats, V2StatsTypedDict
from formance_sdk_python.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class V2StatsResponseTypedDict(TypedDict):
    v2_stats: V2StatsTypedDict


class V2StatsResponse(BaseModel):
    v2_stats: Annotated[V2Stats, pydantic.Field(alias="data")]


try:
    V2StatsResponse.model_rebuild()
except NameError:
    pass
