"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
from formance_sdk_python.models.errors import SDKBaseError
from formance_sdk_python.models.shared import (
    paymentserrorsenum as shared_paymentserrorsenum,
)
from formance_sdk_python.types import BaseModel
import httpx
import pydantic
from typing import Optional
from typing_extensions import Annotated


class PaymentsErrorResponseData(BaseModel):
    error_code: Annotated[
        shared_paymentserrorsenum.PaymentsErrorsEnum, pydantic.Field(alias="errorCode")
    ]

    error_message: Annotated[str, pydantic.Field(alias="errorMessage")]


@dataclass(frozen=True)
class PaymentsErrorResponse(SDKBaseError):
    r"""Error"""

    data: PaymentsErrorResponseData = field(hash=False)

    def __init__(
        self,
        data: PaymentsErrorResponseData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
