"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from formance_sdk_python.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class SnoozeTypedDict(TypedDict):
    r"""A time-boxed, operator-initiated mute of an alert's notifications. While
    `until` is in the future the alert keeps failing and keeps counting
    against period-green — only its notifications are suppressed.

    """

    at: datetime
    by: str
    until: datetime
    note: NotRequired[str]


class Snooze(BaseModel):
    r"""A time-boxed, operator-initiated mute of an alert's notifications. While
    `until` is in the future the alert keeps failing and keeps counting
    against period-green — only its notifications are suppressed.

    """

    at: datetime

    by: str

    until: datetime

    note: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["note"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
