"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .hold_1 import Hold1, Hold1TypedDict
from formance_sdk_python.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class DebitWalletResponseTypedDict(TypedDict):
    hold: Hold1TypedDict


class DebitWalletResponse(BaseModel):
    hold: Annotated[Hold1, pydantic.Field(alias="data")]


try:
    DebitWalletResponse.model_rebuild()
except NameError:
    pass
