"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .wallet import Wallet, WalletTypedDict
from formance_sdk_python.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ListWalletsResponseCursorTypedDict(TypedDict):
    data: List[WalletTypedDict]
    page_size: int
    has_more: NotRequired[bool]
    next: NotRequired[str]
    previous: NotRequired[str]


class ListWalletsResponseCursor(BaseModel):
    data: List[Wallet]

    page_size: Annotated[int, pydantic.Field(alias="pageSize")]

    has_more: Annotated[Optional[bool], pydantic.Field(alias="hasMore")] = None

    next: Optional[str] = None

    previous: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["hasMore", "next", "previous"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ListWalletsResponseTypedDict(TypedDict):
    cursor: ListWalletsResponseCursorTypedDict


class ListWalletsResponse(BaseModel):
    cursor: ListWalletsResponseCursor


try:
    ListWalletsResponseCursor.model_rebuild()
except NameError:
    pass
