"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .assetholder_2 import AssetHolder2, AssetHolder2TypedDict
from formance_sdk_python.types import BaseModel
from formance_sdk_python.utils import validate_int
import pydantic
from pydantic.functional_validators import BeforeValidator
from typing import Dict, List
from typing_extensions import Annotated, TypedDict


class WalletSummaryTypedDict(TypedDict):
    available_funds: Dict[str, int]
    balances: List[AssetHolder2TypedDict]
    expirable_funds: Dict[str, int]
    expired_funds: Dict[str, int]
    hold_funds: Dict[str, int]


class WalletSummary(BaseModel):
    available_funds: Annotated[
        Dict[str, Annotated[int, BeforeValidator(validate_int)]],
        pydantic.Field(alias="availableFunds"),
    ]

    balances: List[AssetHolder2]

    expirable_funds: Annotated[
        Dict[str, Annotated[int, BeforeValidator(validate_int)]],
        pydantic.Field(alias="expirableFunds"),
    ]

    expired_funds: Annotated[
        Dict[str, Annotated[int, BeforeValidator(validate_int)]],
        pydantic.Field(alias="expiredFunds"),
    ]

    hold_funds: Annotated[
        Dict[str, Annotated[int, BeforeValidator(validate_int)]],
        pydantic.Field(alias="holdFunds"),
    ]


try:
    WalletSummary.model_rebuild()
except NameError:
    pass
