"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .assetholder import AssetHolder, AssetHolderTypedDict
from datetime import datetime
from formance_sdk_python.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Dict, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class WalletBalancesTypedDict(TypedDict):
    main: AssetHolderTypedDict


class WalletBalances(BaseModel):
    main: AssetHolder


class WalletTypedDict(TypedDict):
    created_at: datetime
    id: str
    r"""The unique ID of the wallet."""
    ledger: str
    metadata: Dict[str, str]
    r"""Metadata associated with the wallet."""
    name: str
    balances: NotRequired[WalletBalancesTypedDict]


class Wallet(BaseModel):
    created_at: Annotated[datetime, pydantic.Field(alias="createdAt")]

    id: str
    r"""The unique ID of the wallet."""

    ledger: str

    metadata: Dict[str, str]
    r"""Metadata associated with the wallet."""

    name: str

    balances: Optional[WalletBalances] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["balances"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    Wallet.model_rebuild()
except NameError:
    pass
