"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .workflow import Workflow, WorkflowTypedDict
from formance_sdk_python.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class CreateWorkflowResponseTypedDict(TypedDict):
    workflow: WorkflowTypedDict


class CreateWorkflowResponse(BaseModel):
    workflow: Annotated[Workflow, pydantic.Field(alias="data")]


try:
    CreateWorkflowResponse.model_rebuild()
except NameError:
    pass
