"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .hold import Hold, HoldTypedDict
from formance_sdk_python.types import BaseModel
from typing_extensions import TypedDict


class DebitWalletResponseTypedDict(TypedDict):
    data: HoldTypedDict


class DebitWalletResponse(BaseModel):
    data: Hold
