"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .walletwithbalances import WalletWithBalances, WalletWithBalancesTypedDict
from formance_sdk_python.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class GetWalletResponseTypedDict(TypedDict):
    wallet_with_balances: WalletWithBalancesTypedDict


class GetWalletResponse(BaseModel):
    wallet_with_balances: Annotated[WalletWithBalances, pydantic.Field(alias="data")]


try:
    GetWalletResponse.model_rebuild()
except NameError:
    pass
