"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .stagesenddestinationpayment import (
    StageSendDestinationPayment,
    StageSendDestinationPaymentTypedDict,
)
from .stagesendsourceaccount import (
    StageSendSourceAccount,
    StageSendSourceAccountTypedDict,
)
from .stagesendsourcewallet import StageSendSourceWallet, StageSendSourceWalletTypedDict
from formance_sdk_python.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class StageSendDestinationTypedDict(TypedDict):
    account: NotRequired[StageSendSourceAccountTypedDict]
    payment: NotRequired[StageSendDestinationPaymentTypedDict]
    wallet: NotRequired[StageSendSourceWalletTypedDict]


class StageSendDestination(BaseModel):
    account: Optional[StageSendSourceAccount] = None

    payment: Optional[StageSendDestinationPayment] = None

    wallet: Optional[StageSendSourceWallet] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["account", "payment", "wallet"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
