"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .stagesenddestinationpayment import (
    StageSendDestinationPayment,
    StageSendDestinationPaymentTypedDict,
)
from .stagesendsourceaccount import (
    StageSendSourceAccount,
    StageSendSourceAccountTypedDict,
)
from .stagesendsourcewallet import StageSendSourceWallet, StageSendSourceWalletTypedDict
from formance_sdk_python.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class StageSendDestinationTypedDict(TypedDict):
    stage_send_destination_payment: NotRequired[StageSendDestinationPaymentTypedDict]
    stage_send_source_account: NotRequired[StageSendSourceAccountTypedDict]
    stage_send_source_wallet: NotRequired[StageSendSourceWalletTypedDict]


class StageSendDestination(BaseModel):
    stage_send_destination_payment: Annotated[
        Optional[StageSendDestinationPayment], pydantic.Field(alias="payment")
    ] = None

    stage_send_source_account: Annotated[
        Optional[StageSendSourceAccount], pydantic.Field(alias="account")
    ] = None

    stage_send_source_wallet: Annotated[
        Optional[StageSendSourceWallet], pydantic.Field(alias="wallet")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "StageSendDestinationPayment",
                "StageSendSourceAccount",
                "StageSendSourceWallet",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    StageSendDestination.model_rebuild()
except NameError:
    pass
