"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .v2posttransaction import V2PostTransaction, V2PostTransactionTypedDict
from formance_sdk_python.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class V2ActivityCreateTransactionTypedDict(TypedDict):
    v2_post_transaction: NotRequired[V2PostTransactionTypedDict]
    ledger: NotRequired[str]


class V2ActivityCreateTransaction(BaseModel):
    v2_post_transaction: Annotated[
        Optional[V2PostTransaction], pydantic.Field(alias="data")
    ] = None

    ledger: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["V2PostTransaction", "ledger"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    V2ActivityCreateTransaction.model_rebuild()
except NameError:
    pass
