"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .v2workflow import V2Workflow, V2WorkflowTypedDict
from formance_sdk_python.types import BaseModel
from typing_extensions import TypedDict


class V2CreateWorkflowResponseTypedDict(TypedDict):
    data: V2WorkflowTypedDict


class V2CreateWorkflowResponse(BaseModel):
    data: V2Workflow
