"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from formance_sdk_python.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class V2StageSendDestinationPaymentType(str, Enum):
    r"""Type of transfer initiation:
    - TRANSFER: Internal to internal account transfer
    - PAYOUT: Internal to external account payout

    """

    TRANSFER = "TRANSFER"
    PAYOUT = "PAYOUT"


class V2StageSendDestinationPaymentTypedDict(TypedDict):
    psp: str
    r"""Payment service provider name (e.g., stripe, wise, mangopay).
    Validated by the Payments service based on installed connectors.

    """
    source_account: NotRequired[str]
    r"""Formance Payments account ID for the source (internal PSP account).
    If not specified, the Payments service may use a default account for the connector.

    """
    type: NotRequired[V2StageSendDestinationPaymentType]
    r"""Type of transfer initiation:
    - TRANSFER: Internal to internal account transfer
    - PAYOUT: Internal to external account payout

    """


class V2StageSendDestinationPayment(BaseModel):
    psp: str
    r"""Payment service provider name (e.g., stripe, wise, mangopay).
    Validated by the Payments service based on installed connectors.

    """

    source_account: Annotated[Optional[str], pydantic.Field(alias="sourceAccount")] = (
        None
    )
    r"""Formance Payments account ID for the source (internal PSP account).
    If not specified, the Payments service may use a default account for the connector.

    """

    type: Optional[V2StageSendDestinationPaymentType] = (
        V2StageSendDestinationPaymentType.TRANSFER
    )
    r"""Type of transfer initiation:
    - TRANSFER: Internal to internal account transfer
    - PAYOUT: Internal to external account payout

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["sourceAccount", "type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    V2StageSendDestinationPayment.model_rebuild()
except NameError:
    pass
