"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from formance_sdk_python.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class AddAccountToPoolRequestTypedDict(TypedDict):
    account_id: str
    r"""Identifier of the account to add to the pool"""


class AddAccountToPoolRequest(BaseModel):
    account_id: Annotated[str, pydantic.Field(alias="accountID")]
    r"""Identifier of the account to add to the pool"""


try:
    AddAccountToPoolRequest.model_rebuild()
except NameError:
    pass
