"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from formance_sdk_python.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class MangoPayConfigTypedDict(TypedDict):
    api_key: str
    r"""API key issued by MangoPay, used to authenticate the connector's requests"""
    client_id: str
    r"""Client ID issued by MangoPay"""
    endpoint: str
    r"""Base URL of the MangoPay API the connector calls"""
    name: str
    r"""Human-readable name identifying this connector instance"""
    polling_period: NotRequired[str]
    r"""The frequency at which the connector will try to fetch new BalanceTransaction objects from MangoPay API.

    """
    provider: NotRequired[str]
    r"""Identifies the payment provider this configuration targets"""


class MangoPayConfig(BaseModel):
    api_key: Annotated[str, pydantic.Field(alias="apiKey")]
    r"""API key issued by MangoPay, used to authenticate the connector's requests"""

    client_id: Annotated[str, pydantic.Field(alias="clientID")]
    r"""Client ID issued by MangoPay"""

    endpoint: str
    r"""Base URL of the MangoPay API the connector calls"""

    name: str
    r"""Human-readable name identifying this connector instance"""

    polling_period: Annotated[Optional[str], pydantic.Field(alias="pollingPeriod")] = (
        "30m"
    )
    r"""The frequency at which the connector will try to fetch new BalanceTransaction objects from MangoPay API.

    """

    provider: Optional[str] = "Mangopay"
    r"""Identifies the payment provider this configuration targets"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["pollingPeriod", "provider"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    MangoPayConfig.model_rebuild()
except NameError:
    pass
