"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .paymentstatus import PaymentStatus
from datetime import datetime
from formance_sdk_python.types import BaseModel
from formance_sdk_python.utils import validate_int
import pydantic
from pydantic.functional_validators import BeforeValidator
from typing import Any, Dict
from typing_extensions import Annotated, TypedDict


class PaymentAdjustmentTypedDict(TypedDict):
    amount: int
    r"""Amount carried by this adjustment"""
    created_at: datetime
    r"""When the adjustment occurred at the provider"""
    raw: Dict[str, Any]
    r"""The provider's original payload for this adjustment"""
    reference: str
    r"""Identifier the adjustment carries at the provider"""
    status: PaymentStatus
    r"""Where a payment stands in its lifecycle"""


class PaymentAdjustment(BaseModel):
    amount: Annotated[int, BeforeValidator(validate_int)]
    r"""Amount carried by this adjustment"""

    created_at: Annotated[datetime, pydantic.Field(alias="createdAt")]
    r"""When the adjustment occurred at the provider"""

    raw: Dict[str, Any]
    r"""The provider's original payload for this adjustment"""

    reference: str
    r"""Identifier the adjustment carries at the provider"""

    status: PaymentStatus
    r"""Where a payment stands in its lifecycle"""


try:
    PaymentAdjustment.model_rebuild()
except NameError:
    pass
