"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .payment import Payment, PaymentTypedDict
from formance_sdk_python.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PaymentsCursorCursorTypedDict(TypedDict):
    data: List[PaymentTypedDict]
    has_more: bool
    page_size: int
    next: NotRequired[str]
    previous: NotRequired[str]


class PaymentsCursorCursor(BaseModel):
    data: List[Payment]

    has_more: Annotated[bool, pydantic.Field(alias="hasMore")]

    page_size: Annotated[int, pydantic.Field(alias="pageSize")]

    next: Optional[str] = None

    previous: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["next", "previous"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class PaymentsCursorTypedDict(TypedDict):
    r"""OK"""

    cursor: PaymentsCursorCursorTypedDict


class PaymentsCursor(BaseModel):
    r"""OK"""

    cursor: PaymentsCursorCursor


try:
    PaymentsCursorCursor.model_rebuild()
except NameError:
    pass
