"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .transferinitiation import TransferInitiation, TransferInitiationTypedDict
from formance_sdk_python.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TransferInitiationsCursorCursorTypedDict(TypedDict):
    r"""Paginated cursor wrapping the list of transfer initiations"""

    data: List[TransferInitiationTypedDict]
    has_more: bool
    r"""Whether further pages are available"""
    page_size: int
    r"""Number of items requested per page"""
    next: NotRequired[str]
    r"""Cursor for the next page, absent on the last page"""
    previous: NotRequired[str]
    r"""Cursor for the previous page, absent on the first page"""


class TransferInitiationsCursorCursor(BaseModel):
    r"""Paginated cursor wrapping the list of transfer initiations"""

    data: List[TransferInitiation]

    has_more: Annotated[bool, pydantic.Field(alias="hasMore")]
    r"""Whether further pages are available"""

    page_size: Annotated[int, pydantic.Field(alias="pageSize")]
    r"""Number of items requested per page"""

    next: Optional[str] = None
    r"""Cursor for the next page, absent on the last page"""

    previous: Optional[str] = None
    r"""Cursor for the previous page, absent on the first page"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["next", "previous"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class TransferInitiationsCursorTypedDict(TypedDict):
    r"""OK"""

    cursor: TransferInitiationsCursorCursorTypedDict
    r"""Paginated cursor wrapping the list of transfer initiations"""


class TransferInitiationsCursor(BaseModel):
    r"""OK"""

    cursor: TransferInitiationsCursorCursor
    r"""Paginated cursor wrapping the list of transfer initiations"""


try:
    TransferInitiationsCursorCursor.model_rebuild()
except NameError:
    pass
