"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from enum import Enum
from formance_sdk_python.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from formance_sdk_python.utils import validate_int
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import BeforeValidator
from typing import Dict, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TransferInitiationRequestType(str, Enum):
    r"""Whether the funds move between your accounts or out to a third party"""

    TRANSFER = "TRANSFER"
    PAYOUT = "PAYOUT"


class TransferInitiationRequestTypedDict(TypedDict):
    amount: int
    r"""Amount to move, in the asset's smallest unit"""
    asset: str
    r"""Asset the transfer is denominated in"""
    description: str
    r"""Human-readable description carried with the transfer"""
    destination_account_id: str
    r"""Identifier of the account the funds reach"""
    reference: str
    r"""Caller-supplied identifier for the initiation, used to deduplicate retries"""
    scheduled_at: datetime
    r"""When the transfer should be executed"""
    source_account_id: str
    r"""Identifier of the account the funds leave"""
    type: TransferInitiationRequestType
    r"""Whether the funds move between your accounts or out to a third party"""
    validated: bool
    r"""When true, the transfer executes immediately instead of waiting for approval"""
    connector_id: NotRequired[str]
    r"""Identifier of the connector to execute the transfer through"""
    metadata: NotRequired[Nullable[Dict[str, str]]]
    r"""Arbitrary key/value pairs to attach to the initiation"""


class TransferInitiationRequest(BaseModel):
    amount: Annotated[int, BeforeValidator(validate_int)]
    r"""Amount to move, in the asset's smallest unit"""

    asset: str
    r"""Asset the transfer is denominated in"""

    description: str
    r"""Human-readable description carried with the transfer"""

    destination_account_id: Annotated[str, pydantic.Field(alias="destinationAccountID")]
    r"""Identifier of the account the funds reach"""

    reference: str
    r"""Caller-supplied identifier for the initiation, used to deduplicate retries"""

    scheduled_at: Annotated[datetime, pydantic.Field(alias="scheduledAt")]
    r"""When the transfer should be executed"""

    source_account_id: Annotated[str, pydantic.Field(alias="sourceAccountID")]
    r"""Identifier of the account the funds leave"""

    type: TransferInitiationRequestType
    r"""Whether the funds move between your accounts or out to a third party"""

    validated: bool
    r"""When true, the transfer executes immediately instead of waiting for approval"""

    connector_id: Annotated[Optional[str], pydantic.Field(alias="connectorID")] = None
    r"""Identifier of the connector to execute the transfer through"""

    metadata: OptionalNullable[Dict[str, str]] = UNSET
    r"""Arbitrary key/value pairs to attach to the initiation"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["connectorID", "metadata"])
        nullable_fields = set(["metadata"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    TransferInitiationRequest.model_rebuild()
except NameError:
    pass
