"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .legacypaymentstatus import LegacyPaymentStatus
from datetime import datetime
from formance_sdk_python.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import model_serializer
from typing_extensions import Annotated, NotRequired, TypedDict


class TransferInitiationPaymentsTypedDict(TypedDict):
    legacy_payment_status: LegacyPaymentStatus
    created_at: datetime
    payment_id: str
    error: NotRequired[Nullable[str]]


class TransferInitiationPayments(BaseModel):
    legacy_payment_status: Annotated[
        LegacyPaymentStatus, pydantic.Field(alias="status")
    ]

    created_at: Annotated[datetime, pydantic.Field(alias="createdAt")]

    payment_id: Annotated[str, pydantic.Field(alias="paymentID")]

    error: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["error"])
        nullable_fields = set(["error"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    TransferInitiationPayments.model_rebuild()
except NameError:
    pass
