"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from formance_sdk_python.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class V3AddressTypedDict(TypedDict):
    r"""A postal address"""

    city: NotRequired[str]
    r"""City of the address"""
    country: NotRequired[str]
    r"""Country of the address, as an ISO 3166-1 alpha-2 code"""
    postal_code: NotRequired[str]
    r"""Postal or ZIP code of the address"""
    region: NotRequired[str]
    r"""Region, state or province of the address"""
    street_name: NotRequired[str]
    r"""Street name of the address"""
    street_number: NotRequired[str]
    r"""Street number of the address"""


class V3Address(BaseModel):
    r"""A postal address"""

    city: Optional[str] = None
    r"""City of the address"""

    country: Optional[str] = None
    r"""Country of the address, as an ISO 3166-1 alpha-2 code"""

    postal_code: Annotated[Optional[str], pydantic.Field(alias="postalCode")] = None
    r"""Postal or ZIP code of the address"""

    region: Optional[str] = None
    r"""Region, state or province of the address"""

    street_name: Annotated[Optional[str], pydantic.Field(alias="streetName")] = None
    r"""Street name of the address"""

    street_number: Annotated[Optional[str], pydantic.Field(alias="streetNumber")] = None
    r"""Street number of the address"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["city", "country", "postalCode", "region", "streetName", "streetNumber"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    V3Address.model_rebuild()
except NameError:
    pass
