"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .v3bankaccountrelatedaccount import (
    V3BankAccountRelatedAccount,
    V3BankAccountRelatedAccountTypedDict,
)
from datetime import datetime
from formance_sdk_python.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import model_serializer
from typing import Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class V3BankAccountTypedDict(TypedDict):
    created_at: datetime
    id: str
    name: str
    v3_metadata: NotRequired[Nullable[Dict[str, str]]]
    account_number: NotRequired[Nullable[str]]
    country: NotRequired[Nullable[str]]
    iban: NotRequired[Nullable[str]]
    related_accounts: NotRequired[List[V3BankAccountRelatedAccountTypedDict]]
    swift_bic_code: NotRequired[Nullable[str]]


class V3BankAccount(BaseModel):
    created_at: Annotated[datetime, pydantic.Field(alias="createdAt")]

    id: str

    name: str

    v3_metadata: Annotated[
        OptionalNullable[Dict[str, str]], pydantic.Field(alias="metadata")
    ] = UNSET

    account_number: Annotated[
        OptionalNullable[str], pydantic.Field(alias="accountNumber")
    ] = UNSET

    country: OptionalNullable[str] = UNSET

    iban: OptionalNullable[str] = UNSET

    related_accounts: Annotated[
        Optional[List[V3BankAccountRelatedAccount]],
        pydantic.Field(alias="relatedAccounts"),
    ] = None

    swift_bic_code: Annotated[
        OptionalNullable[str], pydantic.Field(alias="swiftBicCode")
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "V3Metadata",
                "accountNumber",
                "country",
                "iban",
                "relatedAccounts",
                "swiftBicCode",
            ]
        )
        nullable_fields = set(
            ["V3Metadata", "accountNumber", "country", "iban", "swiftBicCode"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    V3BankAccount.model_rebuild()
except NameError:
    pass
