"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .v3capability import V3Capability
from datetime import datetime
from formance_sdk_python.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ConfigTypedDict(TypedDict):
    pass


class Config(BaseModel):
    pass


class V3ConnectorTypedDict(TypedDict):
    config: ConfigTypedDict
    created_at: datetime
    id: str
    name: str
    provider: str
    reference: str
    scheduled_for_deletion: bool
    capabilities: NotRequired[List[V3Capability]]
    r"""Plugin capabilities advertised by the connector's provider."""
    updated_at: NotRequired[Nullable[datetime]]


class V3Connector(BaseModel):
    config: Config

    created_at: Annotated[datetime, pydantic.Field(alias="createdAt")]

    id: str

    name: str

    provider: str

    reference: str

    scheduled_for_deletion: Annotated[
        bool, pydantic.Field(alias="scheduledForDeletion")
    ]

    capabilities: Optional[List[V3Capability]] = None
    r"""Plugin capabilities advertised by the connector's provider."""

    updated_at: Annotated[
        OptionalNullable[datetime], pydantic.Field(alias="updatedAt")
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["capabilities", "updatedAt"])
        nullable_fields = set(["updatedAt"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    V3Connector.model_rebuild()
except NameError:
    pass
