"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .v3conversionstatusenum import V3ConversionStatusEnum
from datetime import datetime
from formance_sdk_python.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from formance_sdk_python.utils import validate_int
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import BeforeValidator
from typing import Dict
from typing_extensions import Annotated, NotRequired, TypedDict


class V3ConversionTypedDict(TypedDict):
    r"""A currency or asset conversion executed on a PSP (e.g. Coinbase Prime
    transfer between a USD and USDC wallet). Conversions are read-only in
    the Formance API: they are fetched from the underlying connector.
    Unlike orders, conversions do not carry an adjustment history —
    Formance records the final state only.

    """

    connector_id: str
    r"""ID of the Formance connector this conversion was fetched from."""
    created_at: datetime
    r"""When the conversion was initiated on the PSP."""
    destination_asset: str
    r"""Asset being converted to, in `SYMBOL/precision` form (e.g. `USDC/6`)."""
    id: str
    r"""Formance-assigned unique conversion ID."""
    provider: str
    r"""Provider name of the connector (e.g. `coinbaseprime`)."""
    reference: str
    r"""PSP-assigned conversion reference. Unique within the connector."""
    source_amount: int
    r"""Amount of source asset debited, as an integer at `sourceAsset` precision."""
    source_asset: str
    r"""Asset being converted from, in `SYMBOL/precision` form (e.g. `USD/2`)."""
    status: V3ConversionStatusEnum
    r"""Lifecycle of a conversion.
    `PENDING` — accepted by the PSP, not yet settled.
    `COMPLETED` — settled, terminal.
    `FAILED` — rejected or reverted, terminal. See `error`.

    """
    updated_at: datetime
    r"""When Formance last observed a state change on the conversion."""
    destination_account_id: NotRequired[Nullable[str]]
    r"""Formance account ID of the wallet the destination asset was credited to."""
    destination_amount: NotRequired[Nullable[int]]
    r"""Amount of destination asset credited, at `destinationAsset` precision. Null until the conversion completes."""
    error: NotRequired[Nullable[str]]
    r"""Human-readable error from the PSP when `status` is `FAILED`. Null otherwise."""
    fee: NotRequired[Nullable[int]]
    r"""PSP fee for the conversion, at `feeAsset` precision."""
    fee_asset: NotRequired[Nullable[str]]
    r"""Currency the fee is denominated in, in `SYMBOL/precision` form."""
    metadata: NotRequired[Nullable[Dict[str, str]]]
    r"""Arbitrary key/value pairs attached to the resource"""
    source_account_id: NotRequired[Nullable[str]]
    r"""Formance account ID of the wallet the source asset was debited from."""


class V3Conversion(BaseModel):
    r"""A currency or asset conversion executed on a PSP (e.g. Coinbase Prime
    transfer between a USD and USDC wallet). Conversions are read-only in
    the Formance API: they are fetched from the underlying connector.
    Unlike orders, conversions do not carry an adjustment history —
    Formance records the final state only.

    """

    connector_id: Annotated[str, pydantic.Field(alias="connectorID")]
    r"""ID of the Formance connector this conversion was fetched from."""

    created_at: Annotated[datetime, pydantic.Field(alias="createdAt")]
    r"""When the conversion was initiated on the PSP."""

    destination_asset: Annotated[str, pydantic.Field(alias="destinationAsset")]
    r"""Asset being converted to, in `SYMBOL/precision` form (e.g. `USDC/6`)."""

    id: str
    r"""Formance-assigned unique conversion ID."""

    provider: str
    r"""Provider name of the connector (e.g. `coinbaseprime`)."""

    reference: str
    r"""PSP-assigned conversion reference. Unique within the connector."""

    source_amount: Annotated[
        Annotated[int, BeforeValidator(validate_int)],
        pydantic.Field(alias="sourceAmount"),
    ]
    r"""Amount of source asset debited, as an integer at `sourceAsset` precision."""

    source_asset: Annotated[str, pydantic.Field(alias="sourceAsset")]
    r"""Asset being converted from, in `SYMBOL/precision` form (e.g. `USD/2`)."""

    status: V3ConversionStatusEnum
    r"""Lifecycle of a conversion.
    `PENDING` — accepted by the PSP, not yet settled.
    `COMPLETED` — settled, terminal.
    `FAILED` — rejected or reverted, terminal. See `error`.

    """

    updated_at: Annotated[datetime, pydantic.Field(alias="updatedAt")]
    r"""When Formance last observed a state change on the conversion."""

    destination_account_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="destinationAccountID")
    ] = UNSET
    r"""Formance account ID of the wallet the destination asset was credited to."""

    destination_amount: Annotated[
        Annotated[OptionalNullable[int], BeforeValidator(validate_int)],
        pydantic.Field(alias="destinationAmount"),
    ] = UNSET
    r"""Amount of destination asset credited, at `destinationAsset` precision. Null until the conversion completes."""

    error: OptionalNullable[str] = UNSET
    r"""Human-readable error from the PSP when `status` is `FAILED`. Null otherwise."""

    fee: Annotated[OptionalNullable[int], BeforeValidator(validate_int)] = UNSET
    r"""PSP fee for the conversion, at `feeAsset` precision."""

    fee_asset: Annotated[OptionalNullable[str], pydantic.Field(alias="feeAsset")] = (
        UNSET
    )
    r"""Currency the fee is denominated in, in `SYMBOL/precision` form."""

    metadata: OptionalNullable[Dict[str, str]] = UNSET
    r"""Arbitrary key/value pairs attached to the resource"""

    source_account_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="sourceAccountID")
    ] = UNSET
    r"""Formance account ID of the wallet the source asset was debited from."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "destinationAccountID",
                "destinationAmount",
                "error",
                "fee",
                "feeAsset",
                "metadata",
                "sourceAccountID",
            ]
        )
        nullable_fields = set(
            [
                "destinationAccountID",
                "destinationAmount",
                "error",
                "fee",
                "feeAsset",
                "metadata",
                "sourceAccountID",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    V3Conversion.model_rebuild()
except NameError:
    pass
