"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .v3capability import V3Capability
from formance_sdk_python.types import BaseModel
from typing import Dict, List
from typing_extensions import TypedDict


class V3ConnectorCapabilitiesResponseTypedDict(TypedDict):
    data: Dict[str, List[V3Capability]]
    r"""Map of provider name to the capabilities its plugin advertises."""


class V3ConnectorCapabilitiesResponse(BaseModel):
    data: Dict[str, List[V3Capability]]
    r"""Map of provider name to the capabilities its plugin advertises."""
