"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from formance_sdk_python.types import BaseModel
from typing_extensions import TypedDict


class V3CreatePaymentServiceUserResponseTypedDict(TypedDict):
    data: str
    r"""The ID of the created payment service user"""


class V3CreatePaymentServiceUserResponse(BaseModel):
    data: str
    r"""The ID of the created payment service user"""
