"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .v3task import V3Task, V3TaskTypedDict
from formance_sdk_python.types import BaseModel
from typing_extensions import TypedDict


class V3GetTaskResponseTypedDict(TypedDict):
    data: V3TaskTypedDict


class V3GetTaskResponse(BaseModel):
    data: V3Task
