"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .v3paymentserviceuser import V3PaymentServiceUser, V3PaymentServiceUserTypedDict
from formance_sdk_python.types import BaseModel
from typing_extensions import TypedDict


class V3GetPaymentServiceUserResponseTypedDict(TypedDict):
    data: V3PaymentServiceUserTypedDict


class V3GetPaymentServiceUserResponse(BaseModel):
    data: V3PaymentServiceUser
