"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from formance_sdk_python.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class V3PaymentServiceUserUpdateLinkResponseTypedDict(TypedDict):
    attempt_id: str
    link: str


class V3PaymentServiceUserUpdateLinkResponse(BaseModel):
    attempt_id: Annotated[str, pydantic.Field(alias="attemptID")]

    link: str


try:
    V3PaymentServiceUserUpdateLinkResponse.model_rebuild()
except NameError:
    pass
