"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .v3taskstatusenum import V3TaskStatusEnum
from datetime import datetime
from formance_sdk_python.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class V3TaskTypedDict(TypedDict):
    r"""An asynchronous unit of work, tracking an operation that completes in the background"""

    created_at: datetime
    r"""When the task was created"""
    id: str
    r"""Unique identifier of the task"""
    status: V3TaskStatusEnum
    r"""Where a task stands, from processing through to succeeded or failed"""
    updated_at: datetime
    r"""When the task was last updated"""
    connector_id: NotRequired[str]
    r"""Identifier of the connector the task runs against"""
    created_object_id: NotRequired[str]
    r"""Identifier of the object the task created, once it has succeeded"""
    error: NotRequired[Nullable[str]]
    r"""Why the task failed, absent when it succeeded"""


class V3Task(BaseModel):
    r"""An asynchronous unit of work, tracking an operation that completes in the background"""

    created_at: Annotated[datetime, pydantic.Field(alias="createdAt")]
    r"""When the task was created"""

    id: str
    r"""Unique identifier of the task"""

    status: V3TaskStatusEnum
    r"""Where a task stands, from processing through to succeeded or failed"""

    updated_at: Annotated[datetime, pydantic.Field(alias="updatedAt")]
    r"""When the task was last updated"""

    connector_id: Annotated[Optional[str], pydantic.Field(alias="connectorID")] = None
    r"""Identifier of the connector the task runs against"""

    created_object_id: Annotated[
        Optional[str], pydantic.Field(alias="createdObjectID")
    ] = None
    r"""Identifier of the object the task created, once it has succeeded"""

    error: OptionalNullable[str] = UNSET
    r"""Why the task failed, absent when it succeeded"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["connectorID", "createdObjectID", "error"])
        nullable_fields = set(["error"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    V3Task.model_rebuild()
except NameError:
    pass
