name: Publish
"on":
  push:
    branches:
      - main
    # paths:
    #   - RELEASES.md
jobs:
  Release:
    name: 'Release'
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Get version from gen.yaml
          id: get_version
          uses: mikefarah/yq@master
          with:
            cmd: yq '.python.version' gen.yaml
        - name: Create Release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
          with:
            tag_name: ${{ steps.get_version.outputs.result }}
            release_name: Release ${{ steps.get_version.outputs.result }}
            draft: false
            prerelease: false

  Publish:
    name: 'Publish'
    needs: 
      - Release
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: "3.9"
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install setuptools wheel twine
        - name: Build and publish
          env:
            TWINE_USERNAME: __token__
            TWINE_PASSWORD: ${{ secrets.PYPI_SECRET }}
          run: |
            python setup.py sdist bdist_wheel
            twine upload dist/*
