name: Publish

on:
  push: # Will trigger when the RELEASES.md file is updated by the merged PR from the generation workflow
    paths:
      - 'RELEASES.md'
    branches:
      - main

jobs:
  publish:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/sdk-publish.yaml@v14 # Import the SDK publishing workflow to handle publishing to the package managers
    with:
      publish_python: true # Tells the publishing action to publish the Typescript SDK to NPM
      create_release: true
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      pypi_token:  ${{ secrets.PYPI_SECRET }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
